### ISSUE TITLE
New Lemur install issues (glibc 2.26 / psycopg2 2.7.3 incompatibility)

### ISSUE THREAD

**Issue by pincushionman** [Netflix/lemur#1051]
I'm having an issue with GLIBC and psychopg2 which is fixed in 2.7.3.2 [See psycopg2 issue with glibc here](https://github.com/psycopg/psycopg2-wheels/issues/2)  I've verified that this issue is occurring on Ubuntu 17.10 and Arch Linux

Here's the backtrace:

> (lemur) [lemur@drfate lemur]$ lemur init
Traceback (most recent call last):
  File "/www/lemur/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/www/lemur/lemur/manage.py", line 545, in main
    manager.run()
  File "/www/lemur/lib/python3.6/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/www/lemur/lib/python3.6/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/www/lemur/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/www/lemur/lemur/manage.py", line 189, in run
    create()
  File "/www/lemur/lemur/manage.py", line 139, in create
    database.db.create_all()
  File "/www/lemur/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 972, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/www/lemur/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 964, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/www/lemur/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 910, in get_engine
    return connector.get_engine()
  File "/www/lemur/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 545, in get_engine
    self._engine = rv = sqlalchemy.create_engine(info, **options)
  File "/www/lemur/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 419, in create_engine
    return strategy.create(*args, **kwargs)
  File "/www/lemur/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/www/lemur/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 584, in dbapi
    import psycopg2
  File "/www/lemur/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
    from psycopg2._psycopg import (                     # noqa
ImportError: /www/lemur/lib/python3.6/site-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

I suspected there was something wrong with the db connector, and found a test that suited my needs:
`import psycopg2`
`import subprocess`
`connection = psycopg2.connect(`
`                database='lemur',`
`                user='lemur',`
`                password='lemur',`
`                host='localhost',`
`                port=5432`
`)`
`print(connection.closed) # 0`
`# restart the db externally`
`subprocess.check_call("sudo systemctl restart postgresql", shell=True)`
`# this query will fail because the db is no longer connected`
`try:`
 `       cur = connection.cursor()`
 `       cur.execute('select 1')`
`except psycopg2.OperationalError:`
`        pass`
`print(connection.closed) #2`

I tried their fix:
`pip install psycopg2 --upgrade`
which changes the installed version to 2.7.3.2.  This works with my test.py, but then, `lemur init` then claims that 2.7.3 is no longer installed.

How do I change the requirement to allow 2.7.3.2? I found a lemur.egg and there was a reference to 2.7.3, but changing that (and running make release) didn't seem to help.

**Comment by kevgliss** [comment]
Do we need to update our version of psycopg2?

**Comment by pincushionman** [comment]
For compatibility with glibc 2.26, I would say yes.

The last line of the python 3.6 backtrace had the following to say:
> ImportError: /www/lemur/lib/python3.6/site-packages/psycopg2/.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

When I upgraded it went away.  However, I'm not sure what effect upgrading to 2.7.3.2 would have on glibc 2.25, though.  I don't want to fix it for me (on the bleeding edge) at the expense of everyone else (on stable).

**Comment by kevgliss** [comment]
Would you mind submitting a PR? We can run it through CI and see what happens. I'd rather be proactive if possible.

**Comment by pincushionman** [comment]
Absolutely...  

Uhm - how do I do that?  I'm new to Github.

Oh hey, that's cool - I can tell you what works for me.  That's nice!  Still hazy on what I have to do ...

Okay, I think I muddled my way through it.  Oh man,  I misspelled my tag name.  Oh well, I hope that the updated version works with glibc 2.25.

Thanks again!

**Comment by pincushionman** [comment]
@kevgliss Okay, CI (coveralls?) says that this passes.  Thanks for helping with my first PR!

**Comment by kevgliss** [comment]
You did great! Thanks for the contribution.
