### ISSUE TITLE
Certificate creation failure with cryptography plugin

### ISSUE THREAD

**Issue by dmitryzykov** [Netflix/lemur#1095]
I'm using the latest lemur version from master branch which is running in docker by https://github.com/Netflix/lemur-docker/

I successfully created a new authority with Cryptography plugin in Web UI 
```
Issuing new cryptography authority with options: {'name': 'test', 'common_name': 'test', 'organizational_unit': 'Example', 'description': 'test', 'sensitivity': 'medium', 'plugin': {'plugin_options': [{}], 'plugin_object': <lemur.plugins.lemur_cryptography.plugin.CryptographyIssuerPlugin object at 0x7f1ea2c8d348>, 'slug': 'cryptography-issuer', 'title': 'Cryptography', 'description': 'Enables the creation and signing of self-signed certificates'}, 'serial_number': 1, 'owner': 'test@test.com', 'creator': User(username=lemur), 'location': 'Los Gatos', 'validity_start': <Arrow [2018-03-20T17:31:13.584690+00:00]>, 'country': 'US', 'type': 'root', 'validity_end': <Arrow [2025-03-20T17:31:13.584690+00:00]>, 'organization': 'Example, Inc.', 'state': 'California', 'extensions': {'custom': [], 'basic_constraints': <BasicConstraints(ca=True, path_length=None)>, 'sub_alt_names': {'names': <SubjectAlternativeName(<GeneralNames([])>)>}}, 'first_serial': 1, 'validity_years': 7, 'signing_algorithm': 'sha256WithRSA', 'key_type': 'RSA2048'}
Adding Critical Extension: basic_constraints <BasicConstraints(ca=True, path_length=None)>
Adding Critical Extension: sub_alt_names {'names': <SubjectAlternativeName(<GeneralNames([])>)>}
```

But when I'm trying to create a new certificate using this authority I get an internal server error:
```
[2018-03-20 17:36:44,504] ERROR in app: Exception on /api/1/certificates [POST]
Traceback (most recent call last):
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2848, in one
    ret = self.one_or_none()
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2827, in one_or_none
    "Multiple rows were found for one_or_none()")
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/src/lemur/lemur/auth/service.py", line 135, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/src/lemur/lemur/common/schema.py", line 152, in decorated_function
    data, errors = input_schema.load(request_data)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 580, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 660, in _do_load
    index_errors=self.opts.index_errors,
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 295, in deserialize
    index=(index if index_errors else None)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 68, in call_and_store
    value = getter_func(data)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 288, in <lambda>
    data
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/fields.py", line 265, in deserialize
    output = self._deserialize(value, attr, data)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/fields.py", line 465, in _deserialize
    data, errors = self.schema.load(value)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 580, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 685, in _do_load
    original_data=data)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 858, in _invoke_load_processors
    data=data, many=many, original_data=original_data)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 960, in _invoke_processors
    data = utils.if_none(processor(data), data)
  File "/usr/local/src/lemur/lemur/schemas.py", line 159, in get_object
    return fetch_objects(RotationPolicy, data, many=many)
  File "/usr/local/src/lemur/lemur/schemas.py", line 91, in fetch_objects
    return model.query.filter(getattr(model, attr) == data[attr]).one()
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2851, in one
    "Multiple rows were found for one()")
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()
Exception on /api/1/certificates [POST]
Traceback (most recent call last):
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2848, in one
    ret = self.one_or_none()
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2827, in one_or_none
    "Multiple rows were found for one_or_none()")
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/src/lemur/lemur/auth/service.py", line 135, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/src/lemur/lemur/common/schema.py", line 152, in decorated_function
    data, errors = input_schema.load(request_data)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 580, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 660, in _do_load
    index_errors=self.opts.index_errors,
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 295, in deserialize
    index=(index if index_errors else None)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 68, in call_and_store
    value = getter_func(data)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/marshalling.py", line 288, in <lambda>
    data
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/fields.py", line 265, in deserialize
    output = self._deserialize(value, attr, data)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/fields.py", line 465, in _deserialize
    data, errors = self.schema.load(value)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 580, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 685, in _do_load
    original_data=data)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 858, in _invoke_load_processors
    data=data, many=many, original_data=original_data)
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/marshmallow/schema.py", line 960, in _invoke_processors
    data = utils.if_none(processor(data), data)
  File "/usr/local/src/lemur/lemur/schemas.py", line 159, in get_object
    return fetch_objects(RotationPolicy, data, many=many)
  File "/usr/local/src/lemur/lemur/schemas.py", line 91, in fetch_objects
    return model.query.filter(getattr(model, attr) == data[attr]).one()
  File "/usr/local/src/lemur/venv/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2851, in one
    "Multiple rows were found for one()")
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one()
```

**Comment by kevgliss** [comment]
Interesting, could you give me a rough idea of the values you are POST'ing to the API?

**Comment by dmitryzykov** [comment]
This is my values:
<img width="894" alt="screen shot 2018-03-22 at 12 28 59 pm" src="https://user-images.githubusercontent.com/15911918/37765388-a95c7992-2dcc-11e8-89f4-a7d75eb3cc7e.png">

**Comment by seils** [comment]
@dmitryzykov do you have psql available to query the lemur db directly?  If so, can you provide the output of:
```select * from rotation_policies;```

**Comment by dmitryzykov** [comment]
I can't reproduce this problem with the latest master branch. 
So it seems that this issue is not actual anymore.
