### ISSUE TITLE
issue in creating new certificate(Digicert)

### ISSUE THREAD

**Issue by fruitRollUps** [Netflix/lemur#1490]
I am having trouble retrieving a certificate generated by Digicert through a custom module(using Digicert plugin https://github.com/opendns/lemur-digicert) from Lemur Databse. We have a module that requests/retrieves certificates from Digicert, we are trying to use Lemur as a GUI for that module. I was able to interface directly with Digicert successfully, but when I try to interface Lemur with our module, I am able to get the certificate and I can see the certificate in the Lemur database but the 'certificates' page on Lemur GUI does't load the certificates, not even the ones created earlier, successfully with digicert directly, following is the traceback of that action. Also, I noticed that when I create a certificate through our custom module, I don't see the 'certificate created successfully' notification pop up on the top right corner of Lemur GUI and the form to create the certificate stays there. 

I tried replacing the 'body' value in the table 'certificates' in the database for the one not working with the one created directly from Digicert and then everything works just fine. I thought the certificate body might be having an issue but when I try to parse it using 'openssl' command, it works just fine. Help appreciated, thanks in advance.
 
Unknown SubAltName type: <OtherName(type_id=<ObjectIdentifier(oid=1.3.101.128, name=Unknown OID)>, value=b'\x0c\x0etest-system-ID')>
[2018-07-24 18:34:40,901] ERROR in app: Exception on /api/1/certificates [POST]
Traceback (most recent call last):
  File "/www/lemur/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/lemur/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/lemur/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/www/lemur/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/www/lemur/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
Exception on /api/1/certificates [POST]
Traceback (most recent call last):
  File "/www/lemur/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/lemur/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/www/lemur/lib/python3.6/site-packages/flask_restful/__init__.py", line 484, in wrapper
    return self.make_response(data, code, headers=headers)
  File "/www/lemur/lib/python3.6/site-packages/flask_restful/__init__.py", line 513, in make_response
    resp = self.representations[mediatype](data, *args, **kwargs)
  File "/www/lemur/lib/python3.6/site-packages/flask_restful/representations/json.py", line 21, in output_json
    dumped = dumps(data, **settings) + "\n"
  File "/usr/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

**Comment by fruitRollUps** [comment]
help wanted

**Comment by kevgliss** [comment]
Is this error as a result of creating a new authority or creating a new certificate? Regardless if you think the issue is with the opendns/digicert plugin. Please file an issue there. 

Alternatively there is a build in plugin that should interface just fine with the default digicert API. Here:
https://github.com/Netflix/lemur/blob/master/lemur/plugins/lemur_digicert/plugin.py#L257 

You might try disabling the opendns version and trying the one that comes with `Lemur`.  Docs are located here:

https://lemur.readthedocs.io/en/latest/administration.html?highlight=digicert#digicert-issuer-plugin

**Comment by fruitRollUps** [comment]
Thank you for the quick response. The error occurs while creating a new certificate. I don't think the issue is with the Digicert plugin (I am sure because there is only one file/one method in the plugin that handles the event and I have compared the values/types of all the variables in the method between the working and failure cases, they are similar). I guess its with the way Lemur is handling the certificate during or after persisting. The issue may be either with the certificate or Lemur.

Given that the exception occurs with POST method ( ERROR in app: Exception on /api/1/certificates [POST]) and I don't see the notification popup mentioned 'certificate created successfully', I think though an entry is persisted into 'certificates' table, the process of certificate creation is not completed successfully.

**Comment by kevgliss** [comment]
Saving the certificate to the database is one of the last things that happens, so if you are see it show up there there could be something wrong in the the UI. But the fact that you see a stack trace would lead me to believe that the certificate is not actually getting saved.

Does the browser console show any errors?

**Comment by fruitRollUps** [comment]
the browser console just shows server internal error (500). I think I got a lead, just like the error states, I see a misplaced character in the JSON that has the certificate, I will try to hardcode it just to see if that is the issue and will get back to you. Thank you sir, appreciate it.

**Comment by fruitRollUps** [comment]
As suspected, there was an issue with an extension in the certificate. Thank you kevgliss, appreciate your help.
