### ISSUE TITLE
Is a MySQL Connection to lemur possible?

### ISSUE THREAD

**Issue by Brett-Wood** [Netflix/lemur#1500]
I am attempting to get lemur running using a MySQL database hosted on a separate server than lemur.  I am running into issues with SSL connections and when SSL is disabled I am running into this error:

Plugin 'ACMEIssuerPlugin' may not work correctly. Required variable 'ACME_DIRECTORY_URL' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISSourcePlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Traceback (most recent call last):
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2463, in visit_create_table
    and not first_pk)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 245, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2494, in visit_create_column
    first_pk=first_pk
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1133, in get_column_specification
    column.type, type_expression=column)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 293, in process
    return type_._compiler_dispatch(self, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2933, in visit_string
    return self.visit_VARCHAR(type_, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1540, in visit_VARCHAR
    self.dialect.name)
sqlalchemy.exc.CompileError: VARCHAR requires a length on dialect mysql

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/www/lemur/lemur/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/www/lemur/lemur-master/lemur/manage.py", line 542, in main
    manager.run()
  File "/www/lemur/lemur/lib/python3.6/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/www/lemur/lemur/lib/python3.6/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/www/lemur/lemur/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/www/lemur/lemur-master/lemur/manage.py", line 194, in run
    create()
  File "/www/lemur/lemur-master/lemur/manage.py", line 144, in create
    database.db.create_all()
  File "/www/lemur/lemur/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 963, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/www/lemur/lemur/lib/python3.6/site-packages/flask_sqlalchemy/__init__.py", line 955, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4004, in create_all
    tables=tables)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1940, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1549, in _run_visitor
    **kwargs).traverse_single(element)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 757, in visit_metadata
    _is_metadata_operation=True)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 791, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1003, in _execute_ddl
    if not self.schema_for_object.is_default else None)
  File "<string>", line 1, in <lambda>
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 442, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 26, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 219, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 245, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2474, in visit_create_table
    (table.description, column.name, ce.args[0])
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2463, in visit_create_table
    and not first_pk)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 245, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2494, in visit_create_column
    first_pk=first_pk
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1133, in get_column_specification
    column.type, type_expression=column)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 293, in process
    return type_._compiler_dispatch(self, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/sql/compiler.py", line 2933, in visit_string
    return self.visit_VARCHAR(type_, **kw)
  File "/www/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/base.py", line 1540, in visit_VARCHAR
    self.dialect.name)
sqlalchemy.exc.CompileError: (in table 'rotation_policies', column 'name'): VARCHAR requires a length on dialect mysql

I am just wondering if it is possible to connect lemur to a MySQL database and if so, what are the necessary steps for setting up SSL.  Any advice would be greatly appreciated, thank you.

**Comment by kevgliss** [comment]
Only postgres is support by Lemur.
