### ISSUE TITLE
Unable to create Authority against Hashicorp Vault

### ISSUE THREAD

**Issue by ultimav** [Netflix/lemur#1572]
Looking at the log, it looks like the lemur_vault plugin actually does the work and returns the cert, but lemur throws an exception that the certificate could not be loaded

2018-08-15 15:53:01,541 INFO: Vaule PKI role created successfully. [in /www/lemur/lib/python3.4/site-packages/lemur_vault/plugin.py:181]
2018-08-15 15:53:01,541 INFO: Vault: CA created successfully. [in /www/lemur/lib/python3.4/site-packages/lemur_vault/plugin.py:353]
2018-08-15 15:53:01,543 INFO:  [in /www/lemur/lib/python3.4/site-packages/lemur_vault/plugin.py:360]
2018-08-15 15:53:01,553 ERROR: Unable to load certificate [in /www/lemur/lemur/common/schema.py:162]
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 159, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/authorities/views.py", line 223, in post
    return service.create(**data)
  File "/www/lemur/lemur/authorities/service.py", line 111, in create
    cert = upload(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 235, in upload
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
    File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 417, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/www/lemur/lemur/certificates/models.py", line 145, in __init__
    cert = self.parsed_cert
  File "/www/lemur/lib/python3.4/site-packages/werkzeug/utils.py", line 73, in __get__
    value = self.func(obj)
  File "/www/lemur/lemur/certificates/models.py", line 189, in parsed_cert
    return utils.parse_certificate(self.body)
  File "/www/lemur/lemur/common/utils.py", line 52, in parse_certificate
  File "/www/lemur/lib/python3.4/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/www/lemur/lib/python3.4/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1138, in load_pem_x509_certificate
    raise ValueError("Unable to load certificate ")
ValueError: Unable to load certificate

**Comment by kevgliss** [comment]
Whats the value of `data` here:
```
File "/www/lemur/lib/python3.4/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
return backend.load_pem_x509_certificate(data)
```
That should be a PEM file if it's not or it's malformed, we'd have to dig deeper into why.

**Comment by castrapel** [comment]
Closing this out. Please re-open if you'd like our help debugging further.
