### ISSUE TITLE
Need better error handling around verisign API

### ISSUE THREAD

**Issue by kevgliss** [Netflix/lemur#215]
Sometimes verisign won't even return a response, we should handle this with a better error message.

```
2016-01-13 18:09:44,418 ERROR: 'Response' [in /apps/lemur/lemur/common/utils.py:60]
Traceback (most recent call last):
  File "/apps/lemur/lemur/common/utils.py", line 46, in wrapper
    resp = f(*args, **kwargs)
  File "/apps/lemur/lemur/certificates/views.py", line 386, in post
    return service.create(**args)
  File "/apps/lemur/lemur/certificates/service.py", line 244, in create
    cert, private_key, cert_chain = mint(kwargs)
  File "/apps/lemur/lemur/certificates/service.py", line 151, in mint
    cert_body, cert_chain = issuer.create_certificate(csr, issuer_options)
  File "/apps/lemur/lemur/plugins/lemur_verisign/plugin.py", line 157, in create_certificate
    cert = handle_response(response.content)['Response']['Certificate']
KeyError: 'Response'
```

**Comment by kevgliss** [comment]
This is due to verisign actually trying to read some extensions from the CSR and returning a different kind of certificate.

```2016-01-13 18:33:03,079 DEBUG: Verisign response: <Response xmlns:tns="http://webservices.mpki4ssl.verisign.com"><StatusCode>0x00</StatusCode><Message>success</Message>...<Order type="JavaCodeSigning" orderNumber="847091551" ordered="2" used="2" remaining="0" expiration="DEC 08, 2016" /></Response> [in /apps/lemur/lemur/plugins/lemur_verisign/plugin.py:118]```

We can either support these other types of certificates, or we will have to disable/strip the extension data that is headed for verisign.
