### ISSUE TITLE
Error during certificate export

### ISSUE THREAD

**Issue by tomaszszlek** [Netflix/lemur#223]
I am using Lemur 0.2.1. When I try to export certificate using gui following error is returned by Lemur server : 
```
2016-01-18 10:18:53,794 ERROR: Internal Error [in /usr/local/lib/python2.7/dist-packages/Flask_RESTful-0.3.3-py2.7.egg/flask_restful/__init__.py:299]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/Flask_RESTful-0.3.3-py2.7.egg/flask_restful/__init__.py", line 462, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Flask_RESTful-0.3.3-py2.7.egg/flask_restful/__init__.py", line 572, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/src/lemur/lemur/auth/service.py", line 121, in decorated_function
    return f(*args, **kwargs)
  File "/usr/local/src/lemur/lemur/certificates/views.py", line 855, in post
    extension, passphrase, data = service.export(cert, args['export']['plugin'])
  File "/usr/local/src/lemur/lemur/certificates/service.py", line 91, in export
    return plugin.export(cert.body, cert.chain, cert.private_key, export_plugin['pluginOptions'])
  File "/usr/local/src/lemur/lemur/plugins/lemur_openssl/plugin.py", line 122, in export
    create_pkcs12(body, output_tmp, key, alias, passphrase)
  File "/usr/local/src/lemur/lemur/plugins/lemur_openssl/plugin.py", line 47, in create_pkcs12
    f.write(key)
TypeError: expected a character buffer object

```

**Comment by kevgliss** [comment]
PKCS requires a private key to export, are you sure you have one available to lemur? This should probably be a robust error message.
