### ISSUE TITLE
Issue with hashing passwords

### ISSUE THREAD

**Issue by kevgliss** [Netflix/lemur#259]
Reported by @rpicard. 

There are cases where passwords are coming in as unicode values. They must be decoded before being hashed, described by the following error:

```
2016-03-25 23:05:38,482 ERROR: Internal Error [in /usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py:299]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 462, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 572, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/lemur/lemur/auth/views.py", line 95, in post
    if user and user.check_password(args['password']):
  File "/opt/lemur/lemur/users/models.py", line 56, in check_password
    return bcrypt.check_password_hash(self.password, password)
  File "/usr/local/lib/python2.7/dist-packages/flask_bcrypt.py", line 180, in check_password_hash
    return safe_str_cmp(bcrypt.hashpw(password, pw_hash), pw_hash)
  File "/usr/local/lib/python2.7/dist-packages/bcrypt/__init__.py", line 57, in hashpw
    raise TypeError("Unicode-objects must be encoded before hashing")
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by kevgliss** [comment]
Currently unable to reproduce.
