### ISSUE TITLE
Export certificate error

### ISSUE THREAD

**Issue by suxarik** [Netflix/lemur#2749]
Getting error trying to export cert using any of the plugins. My guess is that is because there is no chain. I can't see chain information on newly created certificate from CFSSL CA, its blank.
Error:
`
[2019-03-28 13:58:17,566] ERROR in schema: 
Traceback (most recent call last):
  File "/usr/local/src/lemur/lemur/common/schema.py", line 161, in decorated_function
    resp = f(*args, **kwargs)
  File "/usr/local/src/lemur/lemur/certificates/views.py", line 1013, in post
    extension, passphrase, data = plugin.export(cert.body, cert.chain, cert.private_key, options)
  File "/usr/local/src/lemur/lemur/plugins/lemur_csr/plugin.py", line 93, in export
    create_csr(body, chain, output_tmp, key)
  File "/usr/local/src/lemur/lemur/plugins/lemur_csr/plugin.py", line 42, in create_csr
    assert isinstance(chain, str)
AssertionError`

**Comment by castrapel** [comment]
Hello, unfortunately we do not use CFSSL internally and thus are unable to support this plugin. 

The primary code contributors appear to be @chadhendrie , @johanneslanger and @alwaysjolley who may be able to investigate.

**Comment by alwaysjolley** [comment]
you need to include your CA certificates in the lemur configuration. See this document for more details
https://www.howtoforge.com/tutorial/integration-of-cfssl-with-the-lemur-certificate-manager/
