### ISSUE TITLE
Issuer Plugin fails to create authority

### ISSUE THREAD

**Issue by rbwrightjr91** [Netflix/lemur#2850]
Here is my `create_authority`:

```
def create_authority(self, options):
        root = open('/path/to/ROOT.crt', 'r').read()

        roles = {
            'username' : '',
            'password' : '',
            'name' : 'Sectigo',
        }
        
        return root, [roles]
```

When I attempt to create an authority with my plugin, I get the following error:

```
[2019-09-05 12:26:36,878] ERROR in schema: local variable 'roles' referenced before assignment
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 160, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/authorities/views.py", line 230, in post
    return service.create(**data)
  File "/www/lemur/lemur/authorities/service.py", line 104, in create
    body, private_key, chain, roles = mint(**kwargs)
  File "/www/lemur/lemur/authorities/service.py", line 57, in mint
    roles,
UnboundLocalError: local variable 'roles' referenced before assignment

```

**Comment by rbwrightjr91** [comment]
Not really sure what the issue was, but it resolved itself. Although, I get validation errors when I try to create the authority via the UI, but I am successful when I do an API call.
