### ISSUE TITLE
New clean Lemur Installation doesn't work

### ISSUE THREAD

**Issue by lirane1** [Netflix/lemur#2855]
Hi,

I installed new clean installation of Lemur, all the interface and login page is working just fine, but the UI is not responsive and in the console I get error messages saying something werkzeug is not working correctly with init error.

I'm not sure how to debug it, any idea?

Thanks.

**Comment by zarfide** [comment]
Can you provide a `pip freeze` of your environment.  In particular we'd interested in what version of `werkzeug` you have I see they released a new version a couple of weeks ago `(0.16.0)` I don't believe we've tried it yet.  Last one I used on my machine was `0.15.4`.

**Comment by CR1AT0RS** [comment]
Same here I am getting this:

>lemur --config=/home/lemur/.lemur/lemur.conf.py start -b 127.0.0.1:8000
[2019-10-04 15:24:15,887] .........
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
[2019-10-04 15:24:15 -0700] [23440] [INFO] Starting gunicorn 19.9.0
[2019-10-04 15:24:15 -0700] [23440] [INFO] Listening at: http://127.0.0.1:8000 (23440)
[2019-10-04 15:24:15 -0700] [23440] [INFO] Using worker: sync
[2019-10-04 15:24:15 -0700] [23446] [INFO] Booting worker with pid: 23446
[2019-10-04 15:24:16,243] WARNING in managers: Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.

[2019-10-04 15:24:16,244] WARNING in managers: Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
[2019-10-04 15:24:18,407] ERROR in __init__: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "/www/lemur/lib/python3.7/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/www/lemur/lib/python3.7/site-packages/werkzeug/routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "/www/lemur/lib/python3.7/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/www/lemur/lib/python3.7/site-packages/werkzeug/routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "/www/lemur/lib/python3.7/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/www/lemur/lib/python3.7/site-packages/werkzeug/routing.py", line 1799, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
^C[2019-10-04 15:24:20 -0700] [23440] [INFO] Handling signal: int
[2019-10-04 15:24:20 -0700] [23446] [INFO] Worker exiting (pid: 23446)
[2019-10-04 15:24:21 -0700] [23440] [INFO] Shutting down: Master

**Comment by CR1AT0RS** [comment]
Same error this is my updated pip freeze that fixed version for Werkzeug (Werkzeug==0.15.6):

> ip(lemur) lemur@ubuntu:/www/lemur/lemur$ pip freeze
> acme==0.39.0
> alembic==1.2.1
> alembic-autogenerate-enums==0.0.2
> amqp==2.5.2
> aniso8601==8.0.0
> arrow==0.15.2
> asn1crypto==1.0.0
> asyncpool==1.0
> bcrypt==3.1.7
> billiard==3.6.1.0
> blinker==1.4
> boto3==1.9.243
> botocore==1.12.243
> celery==4.3.0
> certifi==2019.9.11
> certsrv==2.1.1
> cffi==1.12.3
> chardet==3.0.4
> Click==7.0
> cloudflare==2.3.0
> cryptography==2.7
> dnspython==1.15.0
> dnspython3==1.15.0
> docutils==0.15.2
> dyn==1.8.1
> Flask==1.1.1
> Flask-Bcrypt==0.7.1
> Flask-Cors==3.0.8
> Flask-Mail==0.9.1
> Flask-Migrate==2.5.2
> Flask-Principal==0.4.0
> flask-replicated==1.3
> Flask-RESTful==0.3.7
> Flask-Script==2.0.6
> Flask-SQLAlchemy==2.4.1
> future==0.17.1
> gunicorn==19.9.0
> hvac==0.9.5
> idna==2.8
> inflection==0.3.1
> itsdangerous==1.1.0
> javaobj-py3==0.3.0
> Jinja2==2.10.3
> jmespath==0.9.4
> josepy==1.2.0
> jsonlines==1.2.0
> kombu==4.5.0
> -e git+https://github.com/Netflix/lemur@2239b68e0ec9fd058e49e3fcd03ac21e9780ef8f#egg=lemur
> lockfile==0.12.2
> logmatic-python==0.1.7
> Mako==1.1.0
> MarkupSafe==1.1.1
> marshmallow==2.20.4
> marshmallow-sqlalchemy==0.19.0
> mock==3.0.5
> ndg-httpsclient==0.5.1
> paramiko==2.6.0
> pem==19.2.0
> pip-tools==4.1.0
> psycopg2==2.8.3
> pyasn1==0.4.7
> pyasn1-modules==0.2.6
> pycparser==2.19
> pycryptodomex==3.9.0
> pyjks==19.0.0
> PyJWT==1.7.1
> PyNaCl==1.3.0
> pyOpenSSL==19.0.0
> pyRFC3339==1.1
> python-dateutil==2.8.0
> python-editor==1.0.4
> python-json-logger==0.1.11
> python-ldap==3.2.0
> pytz==2019.2
> PyYAML==5.1.2
> raven==6.10.0
> redis==3.3.8
> requests==2.22.0
> requests-toolbelt==0.9.1
> retrying==1.3.3
> s3transfer==0.2.1
> six==1.12.0
> SQLAlchemy==1.3.9
> SQLAlchemy-Utils==0.34.2
> tabulate==0.8.5
> twofish==0.3.0
> urllib3==1.25.6
> vine==1.3.0
> Werkzeug==0.15.6
> xmltodict==0.12.0

**Comment by CR1AT0RS** [comment]
Same error with version 0.15.4 as well: 
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1925, in dispatch_request
    self.raise_routing_exception(req)
  File "/www/lemur/lib/python3.7/site-packages/flask/app.py", line 1907, in raise_routing_exception
    raise request.routing_exception
  File "/www/lemur/lib/python3.7/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/www/lemur/lib/python3.7/site-packages/werkzeug/routing.py", line 1786, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

Gonna try tomorrow now. Tired

**Comment by keshav372** [comment]
Hello! I am getting the same error as yours with werkzeug 0.16.0. Even after downgrading werkzeug to 0.15.4 it is till the same. Were you able to resolve the issue?

Thanks in advance!

**Comment by xiaopeng-han** [comment]
I am getting the same error as yours with werkzeug 1.0.1. Even after downgrading werkzeug to 0.15.4 it is till the same. 
I'm not sure how to slove it, any idea?

08-11-2020 09:24:43 +0000 WARNING service.py@dce-ctl:123 - Traceback (most recent call last):
  File "flask/app.py", line 1950, in full_dispatch_request
  File "flask/app.py", line 1926, in dispatch_request
  File "flask/app.py", line 1908, in raise_routing_exception
  File "flask/ctx.py", line 350, in match_request
  File "werkzeug/routing.py", line 1786, in match
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by xiaopeng-han** [comment]
My Flask version 1.1.2 , Werkzeug==0.15.4 .it makes some error, how can i do that ?
08-11-2020 09:24:43 +0000 WARNING service.py@dce-ctl:123 - Traceback (most recent call last):
File "flask/app.py", line 1950, in full_dispatch_request
File "flask/app.py", line 1926, in dispatch_request
File "flask/app.py", line 1908, in raise_routing_exception
File "flask/ctx.py", line 350, in match_request
File "werkzeug/routing.py", line 1786, in match
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by gu1113** [comment]
Hi, someone have any lead about how to get rid of this error ?
