### ISSUE TITLE
Unable to create certificates using the CFSSL Issuer Plugin

### ISSUE THREAD

**Issue by rohanmehto2** [Netflix/lemur#2879]
There is an error in creating a certificate using CFSSL as Issuer.

Logs from the lemur server:

```
[2020-01-07 17:46:32,386] ERROR in service: Exception minting certificate
Traceback (most recent call last):
  File "/www/lemur/lemur/certificates/service.py", line 273, in create
    cert_body, private_key, cert_chain, external_id, csr = mint(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 223, in mint
    cert_body, cert_chain, external_id = issuer.create_certificate(csr, kwargs)
  File "/www/lemur/lemur/plugins/lemur_cfssl/plugin.py", line 58, in create_certificate
    key = bytes.fromhex(hex_key)
TypeError: fromhex() argument must be str, not None
Exception minting certificate
Traceback (most recent call last):
  File "/www/lemur/lemur/certificates/service.py", line 273, in create
    cert_body, private_key, cert_chain, external_id, csr = mint(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 223, in mint
    cert_body, cert_chain, external_id = issuer.create_certificate(csr, kwargs)
  File "/www/lemur/lemur/plugins/lemur_cfssl/plugin.py", line 58, in create_certificate
    key = bytes.fromhex(hex_key)
TypeError: fromhex() argument must be str, not None
Exception minting certificate
Traceback (most recent call last):
  File "/www/lemur/lemur/certificates/service.py", line 273, in create
    cert_body, private_key, cert_chain, external_id, csr = mint(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 223, in mint
    cert_body, cert_chain, external_id = issuer.create_certificate(csr, kwargs)
  File "/www/lemur/lemur/plugins/lemur_cfssl/plugin.py", line 58, in create_certificate
    key = bytes.fromhex(hex_key)
TypeError: fromhex() argument must be str, not None
[2020-01-07 17:46:32,387] ERROR in schema: fromhex() argument must be str, not None
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 160, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/certificates/views.py", line 482, in post
    cert = service.create(**data)
  File "/www/lemur/lemur/certificates/service.py", line 273, in create
    cert_body, private_key, cert_chain, external_id, csr = mint(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 223, in mint
    cert_body, cert_chain, external_id = issuer.create_certificate(csr, kwargs)
  File "/www/lemur/lemur/plugins/lemur_cfssl/plugin.py", line 58, in create_certificate
    key = bytes.fromhex(hex_key)
TypeError: fromhex() argument must be str, not None
fromhex() argument must be str, not None
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 160, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/certificates/views.py", line 482, in post
    cert = service.create(**data)
  File "/www/lemur/lemur/certificates/service.py", line 273, in create
    cert_body, private_key, cert_chain, external_id, csr = mint(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 223, in mint
    cert_body, cert_chain, external_id = issuer.create_certificate(csr, kwargs)
  File "/www/lemur/lemur/plugins/lemur_cfssl/plugin.py", line 58, in create_certificate
    key = bytes.fromhex(hex_key)
TypeError: fromhex() argument must be str, not None
fromhex() argument must be str, not None
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 160, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/certificates/views.py", line 482, in post
    cert = service.create(**data)
  File "/www/lemur/lemur/certificates/service.py", line 273, in create
    cert_body, private_key, cert_chain, external_id, csr = mint(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 223, in mint
    cert_body, cert_chain, external_id = issuer.create_certificate(csr, kwargs)
  File "/www/lemur/lemur/plugins/lemur_cfssl/plugin.py", line 58, in create_certificate
    key = bytes.fromhex(hex_key)
TypeError: fromhex() argument must be str, not None
```

**Comment by kevgliss** [comment]
Is `"CFSSL_KEY"` set in your config?

https://github.com/Netflix/lemur/blob/37e58574066921f50485398d195994b1b805c216/lemur/plugins/lemur_cfssl/plugin.py#L57

**Comment by rohanmehto2** [comment]
No, i didn't do that because the exception is handled in code so I thought it would work.
```
try:
            hex_key = current_app.config.get("CFSSL_KEY")
            key = bytes.fromhex(hex_key)
        except (ValueError, NameError):
            # unable to find CFSSL_KEY in config, continue using normal sign method
            pass
```
And also it is not clear to me which key should i pass.
I started my cfssl server using:
`cfssl serve -ca root_ca.pem -ca-key root_ca-key.pem -port 8888`
Any help with this? Which key do i need to put in the config and why is it required now. Because it works fine in the older version (release-0.7).

**Comment by pcaifi** [comment]
@kevgliss What is CFSSL_KEY?

1. Private key that CFSSL is using?
2. Some kind of authentication key?
3. Encrypted Goetia?

Thanks.

**Comment by pcaifi** [comment]
Ah yeah. I found it here. https://lemur.readthedocs.io/en/latest/administration.html

**Comment by rohanmehto2** [comment]
@kevgliss I got what was the problem. Since the CFSSL_KEY is optional, it should work without it too. The problem is not passing the CFSSL_KEY makes its value None rather than being a str, which raises a TypeError. The **TypeError** is not handled in code. Thats why it halts there. Should be corrected.
```
try:
            hex_key = current_app.config.get("CFSSL_KEY")
            key = bytes.fromhex(hex_key)
        except (ValueError, NameError): #TypeError should also be included
            # unable to find CFSSL_KEY in config, continue using normal sign method
            pass
```

**Comment by kevgliss** [comment]
@rohanmehto2 I agree, would you be willing to open a PR? Unfortunately, we don't use CFSSL internally so we have limited ability to test.

**Comment by rohanmehto2** [comment]
@kevgliss sure, i'll do it today after work.
