### ISSUE TITLE
Can't start celery beat & workers

### ISSUE THREAD

**Issue by peschmae** [Netflix/lemur#3147]
After adding the celery configuration according to the documentation, trying to start either the celery beat or worker results in the following error, even after linking the redis container to all lemur containers.

```
Traceback (most recent call last):
  File "/usr/local/src/lemur/venv/lib/python3.6/site-packages/celery/app/utils.py", line 373, in find_app
    sym = symbol_by_name(app, imp=imp)
  File "/usr/local/src/lemur/venv/lib/python3.6/site-packages/celery/bin/base.py", line 534, in symbol_by_name
    return imports.symbol_by_name(name, imp=imp)
  File "/usr/local/src/lemur/venv/lib/python3.6/site-packages/kombu/utils/imports.py", line 62, in symbol_by_name
    return getattr(module, cls_name) if cls_name else module
AttributeError: module 'lemur.common' has no attribute 'celery'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/src/lemur/venv/lib/python3.6/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/src/lemur/venv/lib/python3.6/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/src/lemur/venv/lib/python3.6/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/src/lemur/lemur/common/redis.py", line 31, in redis
    red.set("test", 0)
  File "/usr/local/src/lemur/venv/lib/python3.6/site-packages/redis/client.py", line 1801, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/src/lemur/venv/lib/python3.6/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/src/lemur/venv/lib/python3.6/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/src/lemur/venv/lib/python3.6/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address.
```

It seems like somehow lemur still tries to connect to `localhost:6379`, even though a different redis host ist configured as `CELERY_RESULT_BACKEND` as well as `CELERY_BROKER_URL`

**Comment by peschmae** [comment]
in `lemur/common/redis.py` the RedisHandler opens a connection using the `REDIS_HOST` and `REDIS_PORT` variable, if I set these to the values used for celery, it seems to work.

This should probably be mentioned in the documentation.
