### ISSUE TITLE
Getting DB login error when calling plugin-test

### ISSUE THREAD

**Issue by sirferl** [Netflix/lemur#3158]
I am plagued by a problem:
When calling the plugin Testmdoules I always encounter a DB login problem:
 pytest -v lemur/plugins/lemur_digicert/tests/test_digicert.py
gives (among others):

platform linux -- Python 3.7.7, pytest-6.0.2, py-1.9.0, pluggy-0.13.1 -- /opt/lemur/lemur/bin/python
cachedir: .pytest_cache
rootdir: /opt/lemur, configfile: setup.cfg
plugins: celery-4.4.2, Faker-4.1.3, requests-mock-1.8.0
collected 9 items

lemur/plugins/lemur_digicert/tests/test_digicert.py::test_determine_validity_years PASSED [ 11%]
lemur/plugins/lemur_digicert/tests/test_digicert.py::test_determine_end_date PASSED       [ 22%]
lemur/plugins/lemur_digicert/tests/test_digicert.py::test_map_fields_with_validity_years PASSED [ 33%]
lemur/plugins/lemur_digicert/tests/test_digicert.py::test_map_fields_with_validity_end_and_start PASSED [ 44%]
lemur/plugins/lemur_digicert/tests/test_digicert.py::test_map_cis_fields_with_validity_years ERROR [ 55%]
lemur/plugins/lemur_digicert/tests/test_digicert.py::test_map_cis_fields_with_validity_end_and_start ERROR [ 66%]
lemur/plugins/lemur_digicert/tests/test_digicert.py::test_signature_hash PASSED           [ 77%]
lemur/plugins/lemur_digicert/tests/test_digicert.py::test_issuer_plugin_create_certificate PASSED [ 88%]
lemur/plugins/lemur_digicert/tests/test_digicert.py::test_cancel_ordered_certificate PASSED [100%]

============================================ ERRORS =============================================
___________________ ERROR at setup of test_map_cis_fields_with_validity_years ___________________
Traceback (most recent call last):
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "lemur"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/lemur/lemur/tests/conftest.py", line 78, in db
    _db.drop_all()
  File "/opt/lemur/lemur/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1047, in drop_all
    self._execute_for_all_tables(app, bind, 'drop_all')
  File "/opt/lemur/lemur/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1031, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4347, in drop_all
    ddl.SchemaDropper, self, checkfirst=checkfirst, tables=tables
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2057, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2049, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2251, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2289, in _wrap_pool_connect
    e, dialect, self
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1555, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2285, in _wrap_pool_connect
    return fn()
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 657, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 69, in __exit__
    exc_value, with_traceback=exc_tb,
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 490, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/lemur/lemur/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  password authentication failed for user "lemur"

(Background on this error at: http://sqlalche.me/e/e3q8)
<...further similar messages from other modules ommitted)

**Comment by hosseinsh** [comment]
your db might be busted 

https://github.com/Netflix/lemur/blob/master/Makefile#L41-L49


To be able to run all tests via `make test` you need to install Postgres locally. `make reset-db` should ideally create the DB environment required for the testing, but is it currently assumed Postgres is installed and has the superuser lemur.

```
# macOS
brew services start postgresql
psql lemur -c "CREATE USER lemur with PASSWORD 'lemur';"
psql lemur -c "ALTER USER lemur with superuser;"
psql lemur -c "create extension pg_trgm;"

# Ubuntu
service postgresql status # Verify postgresql is running
service postgresql start # To start if it not running
sudo -u postgres -i
createdb lemur
psql
CREATE USER lemur with PASSWORD 'lemur';
ALTER USER lemur with superuser;
create extension pg_trgm;
```

**Comment by sirferl** [comment]
@hosseinsh Thank you for the explanation. With the default password it works !
