### ISSUE TITLE
Email notification not working

### ISSUE THREAD

**Issue by mherbert84** [Netflix/lemur#323]
Hi Team,

We've just setup Lemur 0.2.2 and now trying to test the email notification functionality.  After importing a self-signed certificate that expires in a few days and running lemur notify, the following appears.

Starting to notify subscribers about expiring certificates!
Finished notifying subscribers about expiring certificates! Sent 0 notifications!

Not entirely sure why this is not working, can any one point me in the right direction?

Thanks

**Comment by kevgliss** [comment]
When you take a look at your imported certificate are there any notifications attached to it?

**Comment by mherbert84** [comment]
Yes, all certificates have Notifications attached.

**Comment by kevgliss** [comment]
It's important to note that the notifications intervals must actually line up. I.e. if you have a certificate that expires in 3 days but your notification says to only alert 2 days before expiration. You will not receive a notification.

**Comment by mherbert84** [comment]
OK that makes sense, I assume the expiration date is for the entire day, not at the specific time the Notify job is run also? I have a cronjob running as per the documentation, but still the notifications are not working, also testing on the basis you mention above (3 day expiration) and running the Notify task manually still materializes in no notifications :(

**Comment by kevgliss** [comment]
Hmm, that's more interesting. Are there any errors in your cron logs? Also are you using a release version or master?

**Comment by mherbert84** [comment]
OK, sorry for the delay in response on this.  Have done more digging, although there is nothing in the cron logs that indicates any kind of issue, when running ./lemur notify I do get an error, see below.  This is release version.

/www/lemur/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
  warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
Starting to notify subscribers about expiring certificates!
Traceback (most recent call last):
  File "./lemur", line 9, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/www/lemur/lemur/manage.py", line 848, in main
    manager.run()
  File "/www/lemur/local/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/www/lemur/local/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/www/lemur/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/www/lemur/lemur/manage.py", line 252, in notify
    count = notification_service.send_expiration_notifications()
  File "/www/lemur/lemur/notifications/service.py", line 89, in send_expiration_notifications
    .filter(Notification.active == True).all()  # noqa
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2588, in all
    return list(self)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2736, in __iter__
    return self._execute_and_instances(context)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2751, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: notifications [SQL: u'SELECT notifications.id AS notifications_id, notifications.label AS notifications_label, notifications.description AS notifications_description, notifications.options AS notifications_options, notifications.active AS notifications_active, notifications.plugin_name AS notifications_plugin_name \nFROM notifications \nWHERE notifications.plugin_name = ? AND notifications.active = 1'] [parameters: ('email-notification',)]

Checking the PostgreSQL database, the table definitely exists.

**Comment by kevgliss** [comment]
So, it looks at though it's looking at sqllite3 database per `(sqlite3.OperationalError)`. I wonder if somewhere in your config you are not point Lemur to the database you think you are. 

Can you double check `SQLALCHEMY_DATABASE_URI` in your config?
