### ISSUE TITLE
Unable to build the Alpine docker image

### ISSUE THREAD

**Issue by red-avtovo** [Netflix/lemur#3253]
Thank you very much for your project! Very excited to use it for my project!
I have some issues though during my initial build of an alpine docker image from `docker` directory
After about 10-20 minutes of installation and configuration of npm packages, I received a bunch of deprecation warnings, but fortunately it didn't block me to continue. When the docker build process was successfully finished, docker composed ran all 3 images (Postgres, redis and lemur itself) and at the first attempt lemur exited with code 2 because it was unable to connect to Postgres db. After I restarted the container it returned me another error which to be honest I have no idea what to do.
Please take a look on the error and explain, what did I do wrong? Did I miss something? I would really like to have a nice alpine image to run.

```
lemur_1     |  ?column?
lemur_1     | ----------
lemur_1     |         1
lemur_1     | (1 row)
lemur_1     |
lemur_1     |  # Create Postgres trgm extension
lemur_1     | NOTICE:  extension "pg_trgm" already exists, skipping
lemur_1     | CREATE EXTENSION
lemur_1     |  # Done
lemur_1     |  # Running init
lemur_1     | Traceback (most recent call last):
lemur_1     |   File "/usr/bin/lemur", line 33, in <module>
lemur_1     |     sys.exit(load_entry_point('lemur', 'console_scripts', 'lemur')())
lemur_1     |   File "/usr/bin/lemur", line 25, in importlib_load_entry_point
lemur_1     |     return next(matches).load()
lemur_1     |   File "/usr/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 105, in load
lemur_1     |     module = import_module(match.group('module'))
lemur_1     |   File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
lemur_1     |     return _bootstrap._gcd_import(name[level:], package, level)
lemur_1     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
lemur_1     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
lemur_1     |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
lemur_1     |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
lemur_1     |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
lemur_1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
lemur_1     |   File "/opt/lemur/lemur/manage.py", line 19, in <module>
lemur_1     |     from lemur.dns_providers.cli import manager as dns_provider_manager
lemur_1     |   File "/opt/lemur/lemur/dns_providers/cli.py", line 6, in <module>
lemur_1     |     from lemur.plugins.lemur_acme.acme_handlers import AcmeDnsHandler
lemur_1     |   File "/opt/lemur/lemur/plugins/lemur_acme/acme_handlers.py", line 19, in <module>
lemur_1     |     import OpenSSL.crypto
lemur_1     |   File "/usr/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
lemur_1     |     from OpenSSL import crypto, SSL
lemur_1     |   File "/usr/lib/python3.6/site-packages/OpenSSL/crypto.py", line 15, in <module>
lemur_1     |     from OpenSSL._util import (
lemur_1     |   File "/usr/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
lemur_1     |     from cryptography.hazmat.bindings.openssl.binding import Binding
lemur_1     |   File "/usr/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 16, in <module>
lemur_1     |     from cryptography.hazmat.bindings._openssl import ffi, lib
lemur_1     | ImportError: Error relocating /usr/lib/python3.6/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: DTLS_client_method: symbol not found
docker_lemur_1 exited with code 1
```

**Comment by peschmae** [comment]
I'd recommend using the docker files available at: https://github.com/Netflix/lemur-docker
They are more recent than the one you ran.

**Comment by peschmae** [comment]
I invested some time to get the build working with alpine, but I think one of the issues is with the openssl/libressl switch that they reverted, and some packages (like python3-dev did switch over to libressl, but cryptography when build using pip not)

It would probably make sense, to switch the dockerfile to Ubuntu similar to the one used in https://github.com/Netflix/lemur-docker/blob/master/web/Dockerfile

**Comment by red-avtovo** [comment]
Thx @sergerdn for the fix. I guess, the issue is resolved now
