### ISSUE TITLE
ACME Revoke Failed

### ISSUE THREAD

**Issue by aashmak** [Netflix/lemur#3255]
'AcmeDnsHandler' object has no attribute 'acme'
Traceback (most recent call last):
  File "/opt/lemur/lemur/common/schema.py", line 160, in decorated_function
    resp = f(*args, **kwargs)
  File "/opt/lemur/lemur/certificates/views.py", line 1444, in put
    plugin.revoke_certificate(cert, data)
  File "/opt/lemur/lemur/plugins/lemur_acme/plugin.py", line 272, in revoke_certificate
    return self.acme.revoke_certificate(certificate)
  File "/opt/lemur/lemur/plugins/lemur_acme/acme_handlers.py", line 227, in revoke_certificate
    acme_client, _ = self.acme.setup_acme_client(certificate.authority)
AttributeError: 'AcmeDnsHandler' object has no attribute 'acme'

This works if the function call:
 acme_client, _ = self.setup_acme_client(certificate.authority)

**Comment by peschmae** [comment]
I'll look into this, I have a decent idea what  I messed up while refactoring.

I should probably also add tests for the certificate revocation.
