### ISSUE TITLE
Trying to connect to ADCS keep getting RSASSA-PSS not supported

### ISSUE THREAD

**Issue by jjason63** [Netflix/lemur#3276]
New to Lemur - we were able to get connected to Let's Encrypt but keep hitting a wall with our ADCS environment.  We rebuilt the internal CA's per Lemur documentation recommendations we found but feel like we're missing something simple.  Any help with this would be great!  Thx.
![Untitled](https://user-images.githubusercontent.com/50631035/100779537-60c08f80-33bd-11eb-844b-13ba30b7e3f7.jpg)

**Comment by sirferl** [comment]
@jjason63 Hello, could you please describe the error in more detail and/or paste the logs from this error? I cannot locate the code snippet you posted.

**Comment by davidhoang-cbre** [comment]
Hi @sirferl - I work with @jjason63.
We upload the cert information into conf.py.  Specifially updating the:
ADCS_SERVER, ADCS_AUTH_METHOD, ADCS_USER, ADCS_PWD, ADCS_TEMPLATE, and ADCS_ROOT.
We then proceed trying to add the Certificate Authority and populate the fields.
Click create and we get an error:
"Was not created! RSASSA-PSS not supported"

from logs:RSASSA-PSS not supported
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 160, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/authorities/views.py", line 230, in post
    return service.create(**data)
  File "/www/lemur/lemur/authorities/service.py", line 133, in create
    cert = upload(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 347, in upload
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/www/lemur/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/www/lemur/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/www/lemur/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/www/lemur/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/www/lemur/lemur/certificates/models.py", line 198, in __init__
    self.issuer = defaults.issuer(cert)
  File "/www/lemur/lemur/common/defaults.py", line 264, in issuer
    if is_selfsigned(cert):
  File "/www/lemur/lemur/common/utils.py", line 267, in is_selfsigned
    check_cert_signature(cert, cert.public_key())
  File "/www/lemur/lemur/common/utils.py", line 236, in check_cert_signature
    raise UnsupportedAlgorithm("RSASSA-PSS not supported")
cryptography.exceptions.UnsupportedAlgorithm: RSASSA-PSS not supported

We can update the /www/lemur/lemur/common/utils.py, /www/lemur/lemur/common/defaults.py, and /www/lemur/lib/python3.8/site-packages/cryptography/hazmat/backends/openssl/x509.py by commenting out sections to bypass this, but obviously that's skipping the checks in place.

Do you have any documentation for ADCS setup?

**Comment by sirferl** [comment]
@davidhoang-cbre @jjason63 hi guys, as I wrote a little earlier: It seems that Lemur cannot handle this kind of signing algorithm for certs in the core, so you will encounter problems with any plugin available.
I propose you try with another one for the root certificate to confirm this.
I have no idea why this kind of certificates is not supported, but the comment hints that it is rather cumbersome to implement handling this kind of certificates. 
I do not maintain the core functions of lemur, so maybe @hosseinsh could shed a bit light on the matter.

**Comment by jjason63** [comment]
@sirferl we really appreciate you getting back to us on this one.  We want to utilize Lemur to the fullest in our environment.  It seems like a solid tool.  Just hitting a few roadblocks on initial deployment.  Probably just our lack of experience with it.  Any guidance @hosseinsh can provide will be appreciated as well.  Thx!

**Comment by sirferl** [comment]
using a certificate with another signing algorithm is no option?

**Comment by sirferl** [comment]
@jjason63 @davidhoang-cbre Any news on this?

**Comment by jjason63** [comment]
Hi @sirferl, thanks for checking in.  We had a working session on Friday to keep attempting to connect Lemur to our ADCS CA but still no luck.  We hit a few new errors that @davidhoang-cbre can upload here first thing Monday.  We have rebuilt our Microsoft CA 3-4x now and tried different signing algorithms but still no luck.  I'm sure we're just missing something simple over here.

Thx

**Comment by davidhoang-cbre** [comment]
Thanks @sirferl - we were able to past the errors by going with a different algorithm.  
Of course, now we have different issues creating a cert.  We'll create a new issue if, needed, thanks!!!

**Comment by sirferl** [comment]
@davidhoang-cbre hello, glad to here you got somethjing going.  @jjason63 wrote about error messages. you could post them here...
