### ISSUE TITLE
bandit error in Travis

### ISSUE THREAD

**Issue by sergerdn** [Netflix/lemur#3391]
We have a 2 problems here:
- bandit errors, it might be a bug on bandit side
- Travis do not report if any errors occurs

I pretty sure that Travis **must** report that build failed if bandit failed for any reason.
```
7.66s$ bandit -r . -ll -ii -x lemur/tests/,docs
1732[main]	INFO	profile include tests: None
1733[main]	INFO	profile exclude tests: None
1734[main]	INFO	cli include tests: None
1735[main]	INFO	cli exclude tests: None
1736[main]	INFO	running on Python 3.7.6
1737309 [0.. [tester]	ERROR	Bandit internal error running: weak_cryptographic_key on file ./lemur/common/utils.py at line 222: list index out of rangeTraceback (most recent call last):
1738  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/bandit/core/tester.py", line 52, in run_tests
1739    result = test(context, test._config)
1740  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/bandit/plugins/weak_cryptographic_key.py", line 129, in weak_cryptographic_key
1741    return (_weak_crypto_key_size_cryptography_io(context, config) or
1742  File "/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/bandit/plugins/weak_cryptographic_key.py", line 105, in _weak_crypto_key_size_cryptography_io
1743    context.call_args[arg_position[key_type]])
1744IndexError: list index out of range
1745
174650.. 100.. 150.. 200.. 250.. 300.. ]
```

**Comment by hosseinsh** [comment]
thanks @sergerdn for noticing this issue and raising it here!

you are right with your observation, that the error is a bandit issue https://github.com/PyCQA/bandit/issues/545
I would also expect Travis would report build failed. We would need to look into that.
