### ISSUE TITLE
PKCS12 Export should enforce private key existence.

### ISSUE THREAD

**Issue by kevgliss** [Netflix/lemur#350]
Currently exporting via the PKCS12 plugin when no private key exists throws: 

```
Traceback (most recent call last):
  File "/apps/lemur/lemur/common/schema.py", line 136, in decorated_function
    resp = f(*args, **kwargs)
  File "/apps/lemur/lemur/certificates/views.py", line 874, in post
    extension, passphrase, data = plugin.export(cert.body, cert.chain, cert.private_key, options)
  File "/apps/lemur/lemur/plugins/lemur_openssl/plugin.py", line 123, in export
    create_pkcs12(body, chain, output_tmp, key, alias, passphrase)
  File "/apps/lemur/lemur/plugins/lemur_openssl/plugin.py", line 48, in create_pkcs12
    f.write(key)
TypeError: expected a character buffer object
```

**Comment by kevgliss** [comment]
Closed in #385.
