### ISSUE TITLE
I can't create a new authority(AttributeError: 'NoneType' object has no attribute 'strip')

### ISSUE THREAD

**Issue by OldBigBuddha** [Netflix/lemur#3810]
Hi all, thank you for creating such a great product.

I'm having trouble now because I can't create a certification authority. When I try to create a new authority, I got a message from lumer. It's `Was not created! 'NoneType' object has no attribute 'strip'` like a screenshot.

![screenshot](https://user-images.githubusercontent.com/13755428/137356697-1a209a36-9b41-4d57-b789-28ca99167d32.png)

I checked my `lumer.log` file. This message is the relevant information maybe:
```json
{
  "asctime": "2021-10-14T15:42:45Z+0000",
  "name": "lemur",
  "processName": "MainProcess",
  "filename": "schema.py",
  "funcName": "decorated_function",
  "levelname": "ERROR",
  "lineno": 161,
  "module": "schema",
  "threadName": "MainThread",
  "message": "'NoneType' object has no attribute 'strip'",
  "exc_info": "Traceback (most recent call last):\n  File \"/www/lemur/lemur/common/schema.py\", line 158, in decorated_function\n    resp = f(*args, **kwargs)\n  File \"/www/lemur/lemur/authorities/views.py\", line 230, in post\n    return service.create(**data)\n  File \"/www/lemur/lemur/authorities/service.py\", line 145, in create\n    cert = upload(**kwargs)\n  File \"/www/lemur/lemur/certificates/service.py\", line 440, in upload\n    cert = Certificate(**kwargs)\n  File \"<string>\", line 4, in __init__\n  File \"/www/lemur/lib/python3.8/site-packages/sqlalchemy/orm/state.py\", line 433, in _initialize_instance\n    manager.dispatch.init_failure(self, args, kwargs)\n  File \"/www/lemur/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py\", line 68, in __exit__\n    compat.raise_(\n  File \"/www/lemur/lib/python3.8/site-packages/sqlalchemy/util/compat.py\", line 182, in raise_\n    raise exception\n  File \"/www/lemur/lib/python3.8/site-packages/sqlalchemy/orm/state.py\", line 430, in _initialize_instance\n    return manager.original_init(*mixed[1:], **kwargs)\n  File \"/www/lemur/lemur/certificates/models.py\", line 199, in __init__\n    self.body = kwargs[\"body\"].strip()\nAttributeError: 'NoneType' object has no attribute 'strip'",
  "timestamp": "2021-10-14T15:42:45Z+0000",
  "hostname": "lemur"
}
```

And beauty `exc_info` is here:
```
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 158, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/authorities/views.py", line 230, in post
    return service.create(**data)
  File "/www/lemur/lemur/authorities/service.py", line 145, in create
    cert = upload(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 440, in upload
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/www/lemur/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/www/lemur/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/www/lemur/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/www/lemur/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/www/lemur/lemur/certificates/models.py", line 199, in __init__
    self.body = kwargs["body"].strip()
AttributeError: 'NoneType' object has no attribute 'strip'
```

My `lemur.conf.py`:
```py
# This is just Python which means you can inherit and tweak settings

import os
_basedir = os.path.abspath(os.path.dirname(__file__))

THREADS_PER_PAGE = 8

# General

# These will need to be set to `True` if you are developing locally
CORS = False
debug = False

# this is the secret key used by flask session management
SECRET_KEY = '<secret>'

# You should consider storing these separately from your config
LEMUR_TOKEN_SECRET = '<token>'
LEMUR_ENCRYPTION_KEYS = '<key>'

# this is the secret used to generate oauth state tokens
OAUTH_STATE_TOKEN_SECRET = b'<token>'

# List of domain regular expressions that non-admin users can issue
LEMUR_ALLOWED_DOMAINS = []

# Mail Server

LEMUR_EMAIL = ''
LEMUR_SECURITY_TEAM_EMAIL = ['sec-term@example.com']

# Certificate Defaults

LEMUR_DEFAULT_COUNTRY = 'JP'
LEMUR_DEFAULT_STATE = 'Tokyo'
LEMUR_DEFAULT_LOCATION = ''
LEMUR_DEFAULT_ORGANIZATION = 'my organization'
LEMUR_DEFAULT_ORGANIZATIONAL_UNIT = ''

# Authentication Providers
ACTIVE_PROVIDERS = []

# Metrics Providers
METRIC_PROVIDERS = []

# Logging

LOG_LEVEL = str(os.environ.get('LOG_LEVEL', 'DEBUG'))
LOG_FILE = str(os.environ.get('LOG_FILE', '/home/lemur/.lemur/lemur.log'))
LOG_UPGRADE_FILE = str(os.environ.get('LOG_FILE', '/home/lemur/.lemur/db_upgrade.log'))
LOG_JSON = True



# Database

# modify this if you are not using a local database
SQLALCHEMY_DATABASE_URI = 'postgresql://lemur:my_secret@localhost:5432/lemur'

# AWS

#LEMUR_INSTANCE_PROFILE = 'Lemur'

# Issuers

# These will be dependent on which 3rd party that Lemur is
# configured to use.

# VERISIGN_URL = ''
# VERISIGN_PEM_PATH = ''
# VERISIGN_FIRST_NAME = ''
# VERISIGN_LAST_NAME = ''
# VERSIGN_EMAIL = ''
```

Does anyone have a good solution for this?
(I am not good at English. If you can't understand my english, please ask me feel free.)

Thanks for reading this far!

**Comment by Paper-Dragon** [comment]
I also have this porblem.
```bash
lemur-docker-lemur-1     | 2022-11-17 08:13:18,044 INFO sqlalchemy.engine.base.Engine {'name_1': '2678885646@qq.com'}
lemur-docker-lemur-1     | [2022-11-17 08:13:18,044] ERROR in schema: 'NoneType' object has no attribute 'strip'
lemur-docker-lemur-1     | Traceback (most recent call last):
lemur-docker-lemur-1     |   File "/opt/lemur/lemur/common/schema.py", line 158, in decorated_function
lemur-docker-lemur-1     |     resp = f(*args, **kwargs)
lemur-docker-lemur-1     |   File "/opt/lemur/lemur/authorities/views.py", line 235, in post
lemur-docker-lemur-1     |     return service.create(**data)
lemur-docker-lemur-1     |   File "/opt/lemur/lemur/authorities/service.py", line 140, in create
lemur-docker-lemur-1     |     cert = upload(**kwargs)
lemur-docker-lemur-1     |   File "/opt/lemur/lemur/certificates/service.py", line 464, in upload
lemur-docker-lemur-1     |     cert = Certificate(**kwargs)
lemur-docker-lemur-1     |   File "<string>", line 4, in __init__
lemur-docker-lemur-1     |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 433, in _initialize_instance
lemur-docker-lemur-1     |     manager.dispatch.init_failure(self, args, kwargs)
lemur-docker-lemur-1     |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
lemur-docker-lemur-1     |     compat.raise_(
lemur-docker-lemur-1     |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
lemur-docker-lemur-1     |     raise exception
lemur-docker-lemur-1     |   File "/opt/venv/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 430, in _initialize_instance
lemur-docker-lemur-1     |     return manager.original_init(*mixed[1:], **kwargs)
lemur-docker-lemur-1     |   File "/opt/lemur/lemur/certificates/models.py", line 193, in __init__
lemur-docker-lemur-1     |     self.body = kwargs["body"].strip()
lemur-docker-lemur-1     | AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by Cronick** [comment]
Same issue here when trying to setup authority with ADCS Issuer.
Following payload will create the give the error, and else creating a new authority with Name, Owner, Description & Common Name.

```
POST /authorities
{
    "country": "US",
    "state": "California",
    "location": "Los Gatos",
    "organization": "Example, Inc.",
    "organizationalUnit": "",
    "defaultIssuerPlugin": null,
    "type": "root",
    "signingAlgorithm": "sha256WithECDSA",
    "sensitivity": "medium",
    "keyType": "ECCPRIME256V1",
    "plugin": {
        "slug": "adcs-issuer",
        "pluginOptions": [],
        "title": "ADCS",
        "description": "Enables the creation of certificates by ADCS (Active Directory Certificate Services)",
        "route": "plugins",
        "reqParams": null,
        "restangularized": true,
        "fromServer": true,
        "parentResource": null,
        "restangularCollection": false
    },
    "extensions": {
        "subAltNames": {
            "names": []
        },
        "custom": [],
        "basicConstraints": {
            "path_length": null,
            "ca": true
        }
    },
    "subAltType": null,
    "subAltValue": null,
    "customOid": null,
    "customIsCritical": null,
    "customEncoding": null,
    "customValue": null,
    "commonName": "IssueTest",
    "owner": "TeamDL@example.com",
    "email": "TeamDL@example.com",
    "name": "IssueTest"
}
```
