### ISSUE TITLE
Bundled plugin tests do not work

### ISSUE THREAD

**Issue by sheurich** [Netflix/lemur#383]
Running `py.test -v` in the lemur/plugins directory fails to pass tests :

```
lemur_aws/tests/test_iam.py::test_get_name_from_arn FAILED
lemur_aws/tests/test_iam.py::test_get_all_server_certs ERROR
lemur_aws/tests/test_iam.py::test_get_cert_from_arn ERROR
lemur_email/tests/test_email.py::test_render FAILED
lemur_java/tests/test_java.py::test_export_certificate_to_jks FAILED
lemur_openssl/tests/test_openssl.py::test_export_certificate_to_jks FAILED
lemur_verisign/tests/test_verisign.py::test_get_certificates FAILED

==================================== ERRORS ====================================
_________________ ERROR at setup of test_get_all_server_certs __________________
file /Users/me/src/lemur/lemur/plugins/lemur_aws/tests/test_iam.py, line 14
  @mock_sts()
  @mock_iam()
  def test_get_all_server_certs(app):
file /usr/local/lib/python3.5/site-packages/pytest_flask/plugin.py, line 96
  @pytest.fixture(autouse=True)
  def _configure_application(request, monkey patch)
        fixture 'app' not found
        available fixtures: tmpdir, accept_jsonp, client, _push_request_context, accept_any, tmpdir_factory, accept_json, capfd, _monkeypatch_response_class, client_class, request_ctx, accept_mimetype, capsys, recwarn, record_xml_property, pytestconfig, config, monkeypatch, live_server, cache, _configure_application
        use 'py.test --fixtures [testpath]' for help on them.

/usr/local/lib/python3.5/site-packages/pytest_flask/plugin.py:96
___________________ ERROR at setup of test_get_cert_from_arn ___________________
file /Users/me/src/lemur/lemur/plugins/lemur_aws/tests/test_iam.py, line 24
  @mock_sts()
  @mock_iam()
  def test_get_cert_from_arn(app):
file /usr/local/lib/python3.5/site-packages/pytest_flask/plugin.py, line 96
  @pytest.fixture(autouse=True)
  def _configure_application(request, monkey patch)
        fixture 'app' not found
        available fixtures: tmpdir, accept_jsonp, client, _push_request_context, accept_any, tmpdir_factory, accept_json, capfd, _monkeypatch_response_class, client_class, request_ctx, accept_mimetype, capsys, recwarn, record_xml_property, pytestconfig, config, monkeypatch, live_server, cache, _configure_application
        use 'py.test --fixtures [testpath]' for help on them.

/usr/local/lib/python3.5/site-packages/pytest_flask/plugin.py:96
=================================== FAILURES ===================================
____________________________ test_get_name_from_arn ____________________________
Traceback (most recent call last):
  File "/Users/me/src/lemur/lemur/plugins/lemur_aws/tests/test_iam.py", line 9, in test_get_name_from_arn
    from lemur.plugins.lemur_aws.iam import get_name_from_arn
  File "/Users/me/src/lemur/lemur/plugins/lemur_aws/iam.py", line 9, in <module>
    from lemur.plugins.lemur_aws.sts import assume_service
  File "/Users/me/src/lemur/lemur/plugins/lemur_aws/sts.py", line 12, in <module>
    import boto3
ImportError: No module named 'boto3'
_________________________________ test_render __________________________________
Traceback (most recent call last):
  File "/Users/me/src/lemur/lemur/plugins/lemur_email/tests/test_email.py", line 16, in test_render
    f.write(body.encode('utf8'))
TypeError: write() argument must be str, not bytes
________________________ test_export_certificate_to_jks ________________________
Traceback (most recent call last):
  File "/Users/me/src/lemur/lemur/plugins/lemur_java/tests/test_java.py", line 60, in test_export_certificate_to_jks
    p = plugins.get('java-export')
  File "/Users/me/src/lemur/lemur/plugins/base/manager.py", line 37, in get
    raise KeyError(slug)
KeyError: 'java-export'
________________________ test_export_certificate_to_jks ________________________
Traceback (most recent call last):
  File "/Users/me/src/lemur/lemur/plugins/lemur_openssl/tests/test_openssl.py", line 60, in test_export_certificate_to_jks
    p = plugins.get('java-export')
  File "/Users/me/src/lemur/lemur/plugins/base/manager.py", line 37, in get
    raise KeyError(slug)
KeyError: 'java-export'
____________________________ test_get_certificates _____________________________
Traceback (most recent call last):
  File "/Users/me/src/lemur/lemur/plugins/lemur_verisign/tests/test_verisign.py", line 4, in test_get_certificates
    p = plugins.get('verisign-source')
  File "/Users/me/src/lemur/lemur/plugins/base/manager.py", line 37, in get
    raise KeyError(slug)
KeyError: 'verisign-source'
====================== 5 failed, 2 error in 1.05 seconds =======================

```::

**Comment by kevgliss** [comment]
I've merged #386 and #385. This should fix the tests. I have also expanded travis such that it should now rull all of the plugin tests as well.
