### ISSUE TITLE
Lemur init dont work von Ubuntu 22.04

### ISSUE THREAD

**Issue by Chiller2019** [Netflix/lemur#4453]
Hey, I follow the Quickstart-Guide from: https://lemur.readthedocs.io/en/latest/quickstart/index.html

My System:
Ubuntu 22.04 LTS
Python3: 3.10.6
Node: 12.22.9
postgresql: 14.8

But it stucks on `lemur init` with the following error:

```

(lemur) lemur@Lemur:/www/lemur/lemur$ lemur init
[2023-06-03 15:39:57,526] WARNING in managers: Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
[2023-06-03 15:39:57,526] WARNING in managers: Plugin 'DigiCertCISSourcePlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISSourcePlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
[2023-06-03 15:39:57,527] WARNING in managers: Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
[2023-06-03 15:39:57,527] WARNING in managers: Plugin 'EntrustIssuerPlugin' may not work correctly. Required variable 'ENTRUST_API_USER' is not set in Lemur's conf.
Plugin 'EntrustIssuerPlugin' may not work correctly. Required variable 'ENTRUST_API_USER' is not set in Lemur's conf.
[2023-06-03 15:39:57,527] WARNING in managers: Plugin 'EntrustSourcePlugin' may not work correctly. Required variable 'ENTRUST_API_USER' is not set in Lemur's conf.
Plugin 'EntrustSourcePlugin' may not work correctly. Required variable 'ENTRUST_API_USER' is not set in Lemur's conf.
Traceback (most recent call last):
  File "/www/lemur/bin/lemur", line 33, in <module>
    sys.exit(load_entry_point('lemur', 'console_scripts', 'lemur')())
  File "/www/lemur/lemur/manage.py", line 603, in main
    manager.run()
  File "/www/lemur/lib/python3.10/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/www/lemur/lib/python3.10/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/www/lemur/lib/python3.10/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/www/lemur/lemur/manage.py", line 203, in run
    create()
  File "/www/lemur/lemur/manage.py", line 154, in create
    stamp(revision="head")
  File "/www/lemur/lib/python3.10/site-packages/flask_migrate/__init__.py", line 96, in wrapped
    f(*args, **kwargs)
  File "/www/lemur/lib/python3.10/site-packages/flask_migrate/__init__.py", line 389, in stamp
    command.stamp(config, revision, sql=sql, tag=tag)
  File "/www/lemur/lib/python3.10/site-packages/alembic/command.py", line 613, in stamp
    script.run_env()
  File "/www/lemur/lib/python3.10/site-packages/alembic/script/base.py", line 563, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/www/lemur/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 92, in load_python_file
    module = load_module_py(module_id, path)
  File "/www/lemur/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 108, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/www/lemur/lemur/migrations/env.py", line 6, in <module>
    import alembic_autogenerate_enums
  File "/www/lemur/lib/python3.10/site-packages/alembic_autogenerate_enums/__init__.py", line 113, in <module>
    class SyncEnumValuesOp(alembic.operations.ops.MigrateOperation):
  File "/www/lemur/lib/python3.10/site-packages/alembic/operations/base.py", line 168, in register
    exec(func_text, globals_, lcl)
  File "<string>", line 1, in <module>
NameError: name 'Tuple' is not defined. Did you mean: 'Type'?
```

Any suggestions?

**Comment by Chiller2019** [comment]
//04.06.2023
Tried LXC with Ubuntu 22.04/20.10 and same with VM.
All LXC/VMs fail at the same command.
