### ISSUE TITLE
Can't register new ACME account

### ISSUE THREAD

**Issue by skorobkov** [Netflix/lemur#4490]
When trying register new account on Let's Encrypt Staging I have got this error
```
Traceback (most recent call last):
  File "/www/lemur/lemur/certificates/service.py", line 495, in create
    cert_body, private_key, cert_chain, external_id, csr = mint(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 436, in mint
    cert_body, cert_chain, external_id = issuer.create_certificate(csr, kwargs)
  File "/www/lemur/lemur/plugins/lemur_acme/plugin.py", line 289, in create_certificate
    return acme_dns_challenge.create_certificate(csr, issuer_options)
  File "/www/lemur/lemur/plugins/lemur_acme/challenge_types.py", line 215, in create_certificate
    acme_client, registration = self.acme.setup_acme_client(authority)
  File "/www/lemur/lib/python3.8/site-packages/retrying.py", line 56, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/www/lemur/lib/python3.8/site-packages/retrying.py", line 266, in call
    raise attempt.get()
  File "/www/lemur/lib/python3.8/site-packages/retrying.py", line 301, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/www/lemur/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/www/lemur/lib/python3.8/site-packages/retrying.py", line 251, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/www/lemur/lemur/plugins/lemur_acme/acme_handlers.py", line 213, in setup_acme_client
    registration = client.new_account_and_tos(
AttributeError: 'ClientV2' object has no attribute 'new_account_and_tos'
```

I believe problem is that acme library (2.6.0) doesn't have `new_account_and_tos` function in ClientV2, it was replaced with `new_account`
https://github.com/certbot/certbot/blob/2.6.x/acme/acme/client.py#L52

**Comment by jmcrawford45** [comment]
@skorobkov thank you for the report and the pointer to the relevant change. I've merged a change to use the `new_account` function instead. Feel free to re-open if you run into similar issues in the future.
