### ISSUE TITLE
Cannot install application

### ISSUE THREAD

**Issue by neilschelly** [Netflix/lemur#450]
Updating gulp-protractor dependency
Following the quickstart instructions at http://lemur.readthedocs.io/en/latest/quickstart/index.html, I ran into issues at `make develop` because several dependencies couldn't be resolved. Several errors like this were in the output in the output:

```
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/share/npm/lib/cache.js:687:35)
npm ERR!     at /usr/share/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-92-generic 
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/lemur/lemur
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type non_object_property_load
```

`npm list` yielded this output at the bottom:
 
```
npm ERR! missing: @types/jasmine@^2.2.31, required by protractor@4.0.9
npm ERR! missing: @types/node@^6.0.35, required by protractor@4.0.9
npm ERR! missing: @types/q@^0.0.30, required by protractor@4.0.9   
npm ERR! missing: @types/selenium-webdriver@~2.53.30, required by protractor@4.0.9
npm ERR! missing: adm-zip@0.4.7, required by protractor@4.0.9
npm ERR! missing: chalk@^1.1.3, required by protractor@4.0.9
npm ERR! missing: glob@^7.0.3, required by protractor@4.0.9
npm ERR! missing: jasmine@2.5.2, required by protractor@4.0.9
npm ERR! missing: jasminewd2@0.0.10, required by protractor@4.0.9
npm ERR! missing: optimist@~0.6.0, required by protractor@4.0.9
npm ERR! missing: q@1.4.1, required by protractor@4.0.9
npm ERR! missing: saucelabs@~1.3.0, required by protractor@4.0.9
npm ERR! missing: selenium-webdriver@2.53.3, required by protractor@4.0.9
npm ERR! missing: source-map-support@~0.4.0, required by protractor@4.0.9
npm ERR! missing: webdriver-manager@^10.2.2, required by protractor@4.0.9
npm ERR! not ok code 0
```

This was on a brand new bare installation of Ubuntu 14.04 on a VM running in VirtualBox/Vagrant. I traced it to this dependency problem, that you'd only run into if you started with no eligible versions of protractor in your NPM package cache.

* lemur depends on gulp-protractor 0.0.11 explicitly
* gulp-protractor 0.0.11 depends on protractor at _any_ version (*)
* The latest versions of protractor (@4) require much newer versions of nodejs (>4) according to the Compatibility section of https://www.npmjs.com/package/protractor.

gulp-protractor 0.0.12 constrains some of these dependencies better, adds a debug option, and fixes a few typos in comments and metadata: https://github.com/mllrsohn/gulp-protractor/compare/0.0.11...0.0.12

**Comment by neilschelly** [comment]
I'm unsure what testing or work is required for this change to be considered, but I can issue a pull request from my own master that resolves this: https://github.com/neilschelly/lemur/
