### ISSUE TITLE
build fails on OSX

### ISSUE THREAD

**Issue by harmw** [Netflix/lemur#581]
Running into an issue when doing a clean `make develop`:

```
$ LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" make develop
[..]
Requirement already satisfied (use --upgrade to upgrade): pycparser in /Users/harm/.virtualenvs/lemur/lib/python2.7/site-packages (from cffi>=1.1.0->cryptography==1.1.2->lemur[tests])
node_modules/.bin/gulp build
module.js:474
    throw err;
    ^

Error: Cannot find module 'imagemin-gifsicle'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/harm/dev/wehkamp/zooi/lemur/node_modules/imagemin/index.js:170:27)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/harm/dev/wehkamp/zooi/lemur/node_modules/gulp-imagemin/index.js:8:16)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
make: *** [develop] Error 1
```

I'm not really into the `node`-game so any help is appreciated 👍

**Comment by harmw** [comment]
I did manage to work around this, using the following:
```
npm install imagemin-gifsicle imagemin-optipng imagemin-pngquant
```

**Comment by kevgliss** [comment]
Can you see if #585 fixes this issue for you?

**Comment by harmw** [comment]
Great, you just fixed it 👍 Gracias!

`LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" make develop` now just works
