### ISSUE TITLE
missing __init__.py in lemur/deployment

### ISSUE THREAD

**Issue by jeremyguarini** [Netflix/lemur#586]
Hi,

I did a fresh checkout and build (since docker instance wasn't building) and found that the lemur create_config failed with the following

>  $ lemur create_config --help
Traceback (most recent call last):
  File "/www/lemur/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/www/lemur/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/www/lemur/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2627, in load_entry_point
    return ep.load()
  File "/www/lemur/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2287, in load
    return self.resolve()
  File "/www/lemur/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2293, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/www/lemur/lemur/manage.py", line 24, in <module>
    from lemur.certificates.cli import manager as certificate_manager
  File "/www/lemur/lemur/certificates/cli.py", line 15, in <module>
    from lemur.deployment.service import rotate_certificate
ImportError: No module named deployment.service

after `touch lemur/deployment/__init__.py` command worked

> $ lemur create_config --help
usage: lemur create_config [-?] [-c CONFIG_PATH]
Creates a new configuration file if one does not already exist
optional arguments:
  -?, --help            show this help message and exit
  -c CONFIG_PATH, --config_path CONFIG_PATH

**Comment by kevgliss** [comment]
Thanks this should be fixed by #587

**Comment by jeremyguarini** [comment]
thanks
