### ISSUE TITLE
Error when downloading a cert: initializer for ctype 'char[]' must be a str or list or tuple, not unicode

### ISSUE THREAD

**Issue by clement-splk** [Netflix/lemur#696]
Looks like it is related to PyOpenSSL issue: pyca/pyopenssl#15

Downloading certs
[2017-02-27 23:31:06,082] ERROR in schema: initializer for ctype 'char[]' must be a str or list or tuple, not unicode
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 158, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/certificates/views.py", line 272, in post
    return service.create(**data)
  File "/www/lemur/lemur/certificates/service.py", line 244, in create
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/www/lemur/lemur/certificates/models.py", line 123, in __init__
    cert = lemur.common.utils.parse_certificate(kwargs['body'])
  File "/www/lemur/lemur/common/utils.py", line 50, in parse_certificate
    return x509.load_pem_x509_certificate(body, default_backend())
  File "/www/lemur/local/lib/python2.7/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/www/lemur/local/lib/python2.7/site-packages/cryptography/hazmat/backends/multibackend.py", line 341, in load_pem_x509_certificate
    return b.load_pem_x509_certificate(data)
  File "/www/lemur/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1169, in load_pem_x509_certificate
    mem_bio = self._bytes_to_bio(data)
  File "/www/lemur/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 490, in _bytes_to_bio
    data_char_p = self._ffi.new("char[]", data)
TypeError: initializer for ctype 'char[]' must be a str or list or tuple, not unicode
initializer for ctype 'char[]' must be a str or list or tuple, not unicode
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 158, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/certificates/views.py", line 272, in post
    return service.create(**data)
  File "/www/lemur/lemur/certificates/service.py", line 244, in create
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/www/lemur/local/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/www/lemur/lemur/certificates/models.py", line 123, in __init__
    cert = lemur.common.utils.parse_certificate(kwargs['body'])
  File "/www/lemur/lemur/common/utils.py", line 50, in parse_certificate
    return x509.load_pem_x509_certificate(body, default_backend())
  File "/www/lemur/local/lib/python2.7/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/www/lemur/local/lib/python2.7/site-packages/cryptography/hazmat/backends/multibackend.py", line 341, in load_pem_x509_certificate
    return b.load_pem_x509_certificate(data)
  File "/www/lemur/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1169, in load_pem_x509_certificate
    mem_bio = self._bytes_to_bio(data)
  File "/www/lemur/local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 490, in _bytes_to_bio
    data_char_p = self._ffi.new("char[]", data)
TypeError: initializer for ctype 'char[]' must be a str or list or tuple, not unicode

**Comment by kevgliss** [comment]
The newest versions of Lemur are python3 only.
