### ISSUE TITLE
Getting error while creating certs with the DigiCert plugin

### ISSUE THREAD

**Issue by clement-splk** [Netflix/lemur#700]
I am getting the following error while creating certs with the DigiCert plugin. The DigiCert plugin was able to load successfully.

I tested my DigiCert API account using curl and the API key and it works fine.

2017-03-02 03:26:19,858 ERROR: 'message' [in /www/lemur/lemur/common/schema.py:160]
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 158, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/certificates/views.py", line 272, in post
    return service.create(**data)
  File "/www/lemur/lemur/certificates/service.py", line 232, in create
    cert_body, private_key, cert_chain = mint(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 181, in mint
    cert_body, cert_chain = issuer.create_certificate(csr, kwargs)
  File "/www/lemur/lemur/plugins/lemur_digicert/plugin.py", line 303, in create_certificate
    raise Exception(response.json()['message'])
KeyError: 'message'

**Comment by clement-splk** [comment]
So the issue is with the "DIGICERT_URL" setting.

In the old OpenDNS DigiCert plugin, this value point to the full API URL:
DIGICERT_URL = 'https://www.digicert.com/services/v2'

I change it to be the base URL and it is working now:
DIGICERT_URL = 'https://www.digicert.com' 

It'd be great if we can have some examples in the documentation so users know what values should be set on these places.

**Comment by kevgliss** [comment]
Makes sense, will try to add some additional documentation. In general all of the Lemur plugins use the root URL leaving it up to the plugin to specify the API version it works with.
