### ISSUE TITLE
RFC 5280 compliance with SAN extension

### ISSUE THREAD

**Issue by neilschelly** [Netflix/lemur#703]
From RFC 5280:

```
   If the subjectAltName extension is present, the sequence MUST contain
   at least one entry.  Unlike the subject field, conforming CAs MUST
   NOT issue certificates with subjectAltNames containing empty
   GeneralName fields.  For example, an rfc822Name is represented as an
   IA5String.  While an empty string is a valid IA5String, such an
   rfc822Name is not permitted by this profile.  The behavior of clients
   that encounter such a certificate when processing a certification
   path is not defined by this profile.
```

Certificates created with Lemur without any SANs are created with an empty list of SANs in the SubjectAlternativeName extension. See here these spots where that's essentially a hard-coded default:

* https://github.com/Netflix/lemur/blob/master/lemur/common/fields.py#L396
* https://github.com/Netflix/lemur/blob/master/lemur/certificates/models.py#L244

I find these work in most places, but I have a suspicion they do not work in OpenJDK 7+ keystores. I am working on confirming this now, but it at least violates the RFC.

**Comment by kevgliss** [comment]
The cryptography plugin is probably most affected by this. External CAs (Digicert, Symantec, etc.) will enforce this behavior by adding whatever is in the common name as a subAltName entry I would assume we could do same.

**Comment by neilschelly** [comment]
Here's some proof:
* CA certificate with no SAN component: https://gist.github.com/neilschelly/1f22eef17e88fb589954b1ccf785424d
* CA certificate with an empty list of SANs: https://gist.github.com/neilschelly/eb51cc6ecb3adc48b16101e59ddbdbd7

The following is the command output of using the Java keytool to parse the empty SAN certificate:

```
$ keytool -printcert -v -file ca-emptysan.crt
keytool error: java.lang.Exception: Failed to parse input
java.lang.Exception: Failed to parse input
        at sun.security.tools.keytool.Main.printCertFromStream(Main.java:2208)
        at sun.security.tools.keytool.Main.doPrintCert(Main.java:2337)
        at sun.security.tools.keytool.Main.doCommands(Main.java:1052)
        at sun.security.tools.keytool.Main.run(Main.java:337)
        at sun.security.tools.keytool.Main.main(Main.java:330)
Caused by: java.security.cert.CertificateParsingException: java.io.IOException: No data available in passed DER encoded value.
        at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:168)
        at sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1779)
        at sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:196)
        at sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:466)
        at sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:352)
        at java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:462)
        at sun.security.tools.keytool.Main.printCertFromStream(Main.java:2206)
        ... 4 more
Caused by: java.io.IOException: No data available in passed DER encoded value.
        at sun.security.x509.GeneralNames.<init>(GeneralNames.java:61)
        at sun.security.x509.SubjectAlternativeNameExtension.<init>(SubjectAlternativeNameExtension.java:141)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
        at sun.security.x509.CertificateExtensions.parseExtension(CertificateExtensions.java:112)
        at sun.security.x509.CertificateExtensions.init(CertificateExtensions.java:88)
        at sun.security.x509.CertificateExtensions.<init>(CertificateExtensions.java:78)
        at sun.security.x509.X509CertInfo.parse(X509CertInfo.java:734)
        at sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:166)
        ... 10 more
```

And for the one lacking the SAN extension entirely:

```
$ keytool -printcert -v -file ca-nosan.crt
Owner: EMAILADDRESS=nschelly@dyn.com, L=Manchester, ST=NH, C=US, OU=Dyn Engineering, O="Oracle + Dyn, Inc", CN=CA-nosans
Issuer: EMAILADDRESS=nschelly@dyn.com, L=Manchester, ST=NH, C=US, OU=Dyn Engineering, O="Oracle + Dyn, Inc", CN=CA-nosans
Serial number: 5b08eccca24a46b89260c38bce156a72
Valid from: Fri Mar 03 16:21:03 UTC 2017 until: Sun Mar 03 16:21:03 UTC 2024
Certificate fingerprints:
         MD5:  96:FA:DB:28:F4:E0:BC:DD:46:18:74:61:92:2F:59:28
         SHA1: 86:41:DC:B5:CA:C8:D0:41:16:7C:80:B3:A8:33:FB:50:90:D7:17:ED
         SHA256: 15:1F:8D:C7:F6:33:5C:98:D3:EF:8A:6B:A8:D4:52:47:24:A4:C7:CB:C0:D2:1E:DA:F5:C5:1A:34:01:81:84:D1
         Signature algorithm name: SHA256withRSA
         Version: 3

Extensions: 

#1: ObjectId: 2.5.29.35 Criticality=false
AuthorityKeyIdentifier [
KeyIdentifier [
0000: 2F B0 39 64 93 55 D9 70   C9 35 CA 3E AB 6F 17 DB  /.9d.U.p.5.>.o..
0010: 11 6D BC A8                                        .m..
]
[EMAILADDRESS=nschelly@dyn.com, L=Manchester, ST=NH, C=US, OU=Dyn Engineering, O="Oracle + Dyn, Inc", CN=CA-nosans]
SerialNumber: [    01]
]

#2: ObjectId: 2.5.29.19 Criticality=true
BasicConstraints:[
  CA:true
  PathLen:2147483647
]

#3: ObjectId: 2.5.29.37 Criticality=false
ExtendedKeyUsages [
  OCSPSigning
]

#4: ObjectId: 2.5.29.15 Criticality=true
KeyUsage [
  Key_CertSign
  Crl_Sign
]

#5: ObjectId: 2.5.29.14 Criticality=false
SubjectKeyIdentifier [
KeyIdentifier [
0000: 2F B0 39 64 93 55 D9 70   C9 35 CA 3E AB 6F 17 DB  /.9d.U.p.5.>.o..
0010: 11 6D BC A8                                        .m..
]
]
```

**Comment by neilschelly** [comment]
I think you're probably right. Here's a couple options for a fix. I can do any of them:

1. Adjust the models/schemas so that you can create a certificate with no SubjectAlternativeName extension. If the list of GeneralNames is empty, it will just skip adding that extension.
1. Adjust the lemur_cryptography plugin code so that if there is a SubjectAlternativeName extension with no GeneralNames in it, it will create a GeneralName from the Subject CN and add that to the SAN extension.
1. Adjust the models/schemas so that there will _always_ be a SubjectAlternativeName extension. Unless it is already present in the list of SAN GeneralNames, it will add the CN from the Subject to the SAN extension.

The first option allows for a certificate without a SubjectAlternativeName extension. That's perhaps not practically useful for typical uses of certificates to protect websites, but could satisfy someone's edge case where they want certificates without that extension defined.

The second option lets the plugins handle an empty SAN extension all by themselves, however they see fit. Most third-party ones will handle this gracefully and put the Subject CN into the SAN extension. We could fix the cryptography plugin to match this behavior.

The third option ensures that all CSRs that are created by the Lemur can become RFC-compliant certificates once they are signed, without depending on the plugin or third party to do it for them.

I'm a fan of the second option myself, which seems easiest to implement and matches your comment. I'll try making that happen with a PR soon.

**Comment by kevgliss** [comment]
I think option 2 is okay for now as it aligns cryptography with the other issuers.
