### ISSUE TITLE
Unable to create authority

### ISSUE THREAD

**Issue by gunjanvarshney** [Netflix/lemur#758]
Hi,

I am trying to get Lemur up and running for internal use in my company. The inital idea is to use Lemur for automating certificate generation and distribution to our nodes for internal security.

While creating an authority using CFSSL plugin I get following error:

[2017-04-24 14:40:17,169] ERROR in schema: Unable to load certificate
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 158, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/authorities/views.py", line 223, in post
    return service.create(**data)
  File "/www/lemur/lemur/authorities/service.py", line 108, in create
    cert = upload(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 220, in upload
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/www/lemur/lemur/certificates/models.py", line 125, in __init__
    cert = lemur.common.utils.parse_certificate(kwargs['body'])
  File "/www/lemur/lemur/common/utils.py", line 53, in parse_certificate
    return x509.load_pem_x509_certificate(body, default_backend())
  File "/www/lemur/lib/python3.4/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/www/lemur/lib/python3.4/site-packages/cryptography/hazmat/backends/multibackend.py", line 341, in load_pem_x509_certificate
    return b.load_pem_x509_certificate(data)
  File "/www/lemur/lib/python3.4/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1175, in load_pem_x509_certificate
    raise ValueError("Unable to load certificate")
ValueError: Unable to load certificate
Unable to load certificate
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 158, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/authorities/views.py", line 223, in post
    return service.create(**data)
  File "/www/lemur/lemur/authorities/service.py", line 108, in create
    cert = upload(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 220, in upload
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/www/lemur/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/www/lemur/lemur/certificates/models.py", line 125, in __init__
    cert = lemur.common.utils.parse_certificate(kwargs['body'])
  File "/www/lemur/lemur/common/utils.py", line 53, in parse_certificate
    return x509.load_pem_x509_certificate(body, default_backend())
  File "/www/lemur/lib/python3.4/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/www/lemur/lib/python3.4/site-packages/cryptography/hazmat/backends/multibackend.py", line 341, in load_pem_x509_certificate
    return b.load_pem_x509_certificate(data)
  File "/www/lemur/lib/python3.4/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1175, in load_pem_x509_certificate
    raise ValueError("Unable to load certificate")
ValueError: Unable to load certificate

What can I do now.

**Comment by kevgliss** [comment]
Please ensure that the following values are set in your lemur.conf:

http://lemur.readthedocs.io/en/latest/administration.html?highlight=CFssl#cfssl-issuer-plugin

**Comment by bfennimore** [comment]
What is the syntax for those values?  Common names?  Paths to a pem file?

**Comment by kevgliss** [comment]
They are strings, if you want to read from a file you can use `open('myfile.txt', 'r').read()`.

**Comment by bfennimore** [comment]
Thank you.  Providing the public certificate via a file solved my errors.

**Comment by gunjanvarshney** [comment]
Appolgies for coming back again on this and that too so late. I did try to stick in the pem formated string in the CFSSL_ROOT parameter but I still get the same error

**Comment by kevgliss** [comment]
@gunjanvarshney do you have the other values defined per the docs? What version of Lemur are you running?

**Comment by gunjanvarshney** [comment]
I am not sure what version is lemur as I followed steps on http://lemur.readthedocs.io/en/latest/quickstart/ but on centos. there would be dependencies differences but I was able to make it.

I have following in my ~/.lemur/lemur.conf.py file

CFSSL_URL = <defined something>
CFSSL_ROOT = <defined as certificate string in PEM format>
CFSSL_INTERMEDIATE = <not defined>

**Comment by kevgliss** [comment]
Are the above variables set? Do they have values?

**Comment by gunjanvarshney** [comment]
yes both URL and Root have values. intermediate doesnt. do you want me to send the details.

**Comment by kevgliss** [comment]
Make sure you are including the entire PEM file.

It should look something like:
CFSSL_ROOT="""-----BEGIN CERTIFICATE-----
MIIEGjCCAwICEQCbfgZJoz5iudXukEhxKe9XMA0GCSqGSIb3DQEBBQUAMIHKMQsw
...
TxzhT5yvDwyd93gN2PQ1VoDat20Xj50egWTh/sVFuq1ruQp6Tk9LhO5L8X3dEQ==
-----END CERTIFICATE-----
"""
