### ISSUE TITLE
Missing python dependencies : packaging and appdirs

### ISSUE THREAD

**Issue by arthurlogilab** [Netflix/lemur#789]
Following install procedure in http://lemur.readthedocs.io/en/latest/quickstart/index.html

I get 

```
# make release
[snip]
  Found existing installation: setuptools 5.5.1
    Uninstalling setuptools:
      Successfully uninstalled setuptools
  Running setup.py install for cffi
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/var/www/lemur/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>
        import setuptools.version
      File "/var/www/lemur/lib/python3.4/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/var/www/lemur/lib/python3.4/site-packages/pkg_resources/__init__.py", line 70, in <module>
        import packaging.version
    ImportError: No module named 'packaging'
    Complete output from command /var/www/lemur/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-w_eavuwc/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5rbl8dxo-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/lemur/include/site/python3.4:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/var/www/lemur/lib/python3.4/site-packages/setuptools/__init__.py", line 12, in <module>

    import setuptools.version

  File "/var/www/lemur/lib/python3.4/site-packages/setuptools/version.py", line 1, in <module>

    import pkg_resources

  File "/var/www/lemur/lib/python3.4/site-packages/pkg_resources/__init__.py", line 70, in <module>

    import packaging.version

ImportError: No module named 'packaging'

----------------------------------------
Cleaning up...
Command /var/www/lemur/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-w_eavuwc/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-5rbl8dxo-record/install-record.txt --single-version-externally-managed --compile --install-headers /var/www/lemur/include/site/python3.4 failed with error code 1 in /tmp/pip-build-w_eavuwc/cffi
Storing debug log for failure in /home/lemur/.pip/pip.log
Makefile:24: recipe for target 'release' failed
make: *** [release] Error 1
```

Solved by doing : 
```
pip install packaging
```

Then the same occurs with appdirs (same fix)

**Comment by arthurlogilab** [comment]
Then create_config misses some dependencies too 

```
(lemur)lemur@lemur:/var/www/lemur$ lemur create_config
Traceback (most recent call last):
  File "/var/www/lemur/bin/lemur", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/var/www/lemur/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/var/www/lemur/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/var/www/lemur/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/var/www/lemur/lib/python3.4/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/var/www/lemur/lib/python3.4/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/var/www/lemur/lib/python3.4/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyrfc3339' distribution was not found and is required by acme
(lemur)lemur@lemur:/var/www/lemur$ pip install pyrfc3339
Downloading/unpacking pyrfc3339
  Downloading pyRFC3339-1.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pytz in ./lib/python3.4/site-packages (from pyrfc3339)
Installing collected packages: pyrfc3339
Successfully installed pyrfc3339
Cleaning up...
```
Solved with 
```
$ history | grep pip 
   13  pip install packaging
   16  pip install appdirs
   19  pip install pyrfc3339
   24  pip install mock
   27  pip install 'jmespath<1.0.0,>=0.7.1'
   29  pip install 's3transfer<0.2.0,>=0.1.10'
```

**Comment by kevgliss** [comment]
I wonder if you are running into this:

https://github.com/pypa/setuptools/issues/937
