### ISSUE TITLE
TypeError: 'NoneType' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by martindube** [Netflix/lemur#837]
Hi,

I am having an error on fresh install when creating a new CA. I have followed the documentation for installation. This is running on:

  - FreeBSD 11.0-RELEASE-p9 x64
  - Python 3.6.1 
  - Postgresql 9.6.3

```
Traceback (most recent call last):
  File "/home/lemur/lemur/lemur/common/schema.py", line 158, in decorated_function
    resp = f(*args, **kwargs)
  File "/home/lemur/lemur/lemur/authorities/views.py", line 223, in post
    return service.create(**data)
  File "/home/lemur/lemur/lemur/authorities/service.py", line 108, in create
    cert = upload(**kwargs)
  File "/home/lemur/lemur/lemur/certificates/service.py", line 220, in upload
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/home/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/home/lemur/lemur/lib/python3.6/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/lemur/lemur/lemur/certificates/models.py", line 125, in __init__
    cert = lemur.common.utils.parse_certificate(kwargs['body'])
  File "/home/lemur/lemur/lemur/common/utils.py", line 53, in parse_certificate
    return x509.load_pem_x509_certificate(body, default_backend())
  File "/home/lemur/lemur/lib/python3.6/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/home/lemur/lemur/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1063, in load_pem_x509_certificate
    mem_bio = self._bytes_to_bio(data)
  File "/home/lemur/lemur/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 432, in _bytes_to_bio
    data_char_p = self._ffi.new("char[]", data)
TypeError: 'NoneType' object cannot be interpreted as an integer
```

Behavior:

![image](https://user-images.githubusercontent.com/4238786/27355666-e15d84ba-55d9-11e7-8a37-c883fbd2c314.png)

**Comment by martindube** [comment]
Same issue when using Python 2.7.13.

**Comment by kevgliss** [comment]
Which plugin are you using, if you click on more options it should say. This occurs most often when you're attempting to use a plugin that isn't configured correctly.

**Comment by martindube** [comment]
I used the CFSSL plugin with default configuration.

When changing to Cryptography plugin, I get this error: 

```
Traceback (most recent call last):
  File "/home/lemur/lemur/lemur/common/schema.py", line 158, in decorated_function
    resp = f(*args, **kwargs)
  File "/home/lemur/lemur/lemur/authorities/views.py", line 223, in post
    return service.create(**data)
  File "/home/lemur/lemur/lemur/authorities/service.py", line 108, in create
    cert = upload(**kwargs)
  File "/home/lemur/lemur/lemur/certificates/service.py", line 220, in upload
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/home/lemur/lemur/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/home/lemur/lemur/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/lemur/lemur/lib/python2.7/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/home/lemur/lemur/lemur/certificates/models.py", line 125, in __init__
    cert = lemur.common.utils.parse_certificate(kwargs['body'])
  File "/home/lemur/lemur/lemur/common/utils.py", line 53, in parse_certificate
    return x509.load_pem_x509_certificate(body, default_backend())
  File "/home/lemur/lemur/lib/python2.7/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/home/lemur/lemur/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1063, in load_pem_x509_certificate
    mem_bio = self._bytes_to_bio(data)
  File "/home/lemur/lemur/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 432, in _bytes_to_bio
    data_char_p = self._ffi.new("char[]", data)
TypeError: initializer for ctype 'char[]' must be a str or list or tuple, not unicode
```

**Comment by martindube** [comment]
Cryptography Plugin seems to work on Python 3.6. I will do more tests and let you know if I find other bugs.

**Comment by kevgliss** [comment]
The above stacktrace is using python2.7 which Lemur does not support, when using the CFSSL plugin please make sure the following configuration variables are set:

http://lemur.readthedocs.io/en/latest/administration.html#cfssl-issuer-plugin

**Comment by martindube** [comment]
Thanks for the reply. You are correct, it was a test with Python2.7. I fixed the issue by using the Cryptography plugin and using Python3.6. I succesfully created a root CA, sub CA and server and client certificates. This apps looks great !

Can I suggest to put "Cryptography" as a default plugin? CFSSL was the default (maybe due to alphabetic order). Also, I believe that handling this kind of error would have benefits on the project. Otherwise, the issue can be closed.

Thank you!

**Comment by kevgliss** [comment]
Yes, there is no preference to the plugins currently. I will create another issue with that as an enhancement. Just a note; the Cryptography plugin is generally okay for testing Lemur but is not recommended for a production use case. This is because you would generally want to keep an internal CAs root keys in something like an HSM which Lemur does not currently support.
