### ISSUE TITLE
UnboundLocalError: local variable 'notification' referenced before assignment

### ISSUE THREAD

**Issue by RickB17** [Netflix/lemur#859]
``` lemur notify expirations ``` fails to execute with the output below

```
(lemur-dev) lemur@SERVER-NAME:/www/lemur-dev/lemur$ lemur notify expirations
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'ACMEIssuerPlugin' may not work correctly. Required variable 'ACME_DIRECTORY_URL' is not set in Lemur's conf.
Starting to notify subscribers about expiring certificates!
Traceback (most recent call last):
  File "/www/lemur-dev/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/www/lemur-dev/lemur/manage.py", line 534, in main
    manager.run()
  File "/www/lemur-dev/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/www/lemur-dev/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/www/lemur-dev/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/www/lemur-dev/lemur/notifications/cli.py", line 24, in expirations
    success, failed = send_expiration_notifications()
  File "/www/lemur-dev/lemur/notifications/messaging.py", line 123, in send_expiration_notifications
    if send_notification('expiration', security_data, security_email, notification):
UnboundLocalError: local variable 'notification' referenced before assignment

```

**Comment by RickB17** [comment]
This appears to be related to the needs_notification function passing when the unit is set to days.

**Comment by kevgliss** [comment]
I believe this has already been fixed via: https://github.com/Netflix/lemur/commit/1c295896e6f412b0515a03de53a1612a3a71ba8c

**Comment by RickB17** [comment]
@kevgliss Any suggestions on resolving this database upgrade issue while attempting to upgrade to the latest release?

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) enum label "create_cert" already exists
 [SQL: "ALTER TYPE log_type ADD VALUE 'create_cert'"]
```


**DETAILS**

```
(lemur-dev) lemur@SERVERNAME:/www/lemur-dev/lemur$ lemur -c /home/lemur/.lemur-dev/lemur.conf.py db upgrade
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'ACMEIssuerPlugin' may not work correctly. Required variable 'ACME_DIRECTORY_URL' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 5e680529b666 -> 8ae67285ff14, Modifies the unique index for the certificate replacements
INFO  [alembic.runtime.migration] Running upgrade 8ae67285ff14 -> a02a678ddc25, Adds support for rotation policies.
INFO  [alembic.runtime.migration] Running upgrade a02a678ddc25 -> 1ae8e3104db8, Adds additional ENUM for creating and updating certificates.
/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/engine/default.py:428: SAWarning: Connection is already established with a Transaction; setting isolation_level may implicitly rollback or commit the existing transaction, or have no effect until next transaction
  "Connection is already established with a Transaction; "
Traceback (most recent call last):
  File "/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: enum label "create_cert" already exists


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/www/lemur-dev/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/www/lemur-dev/lemur/manage.py", line 545, in main
    manager.run()
  File "/www/lemur-dev/lib/python3.5/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/www/lemur-dev/lib/python3.5/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/www/lemur-dev/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/www/lemur-dev/lib/python3.5/site-packages/flask_migrate/__init__.py", line 247, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/www/lemur-dev/lib/python3.5/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/www/lemur-dev/lib/python3.5/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/www/lemur-dev/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/www/lemur-dev/lib/python3.5/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 72, in <module>
    run_migrations_online()
  File "migrations/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/www/lemur-dev/lib/python3.5/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/www/lemur-dev/lib/python3.5/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/www/lemur-dev/lemur/migrations/versions/1ae8e3104db8_.py", line 23, in upgrade
    op.execute("ALTER TYPE log_type ADD VALUE 'create_cert'")
  File "<string>", line 8, in execute
  File "<string>", line 3, in execute
  File "/www/lemur-dev/lib/python3.5/site-packages/alembic/operations/ops.py", line 1842, in execute
    return operations.invoke(op)
  File "/www/lemur-dev/lib/python3.5/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/www/lemur-dev/lib/python3.5/site-packages/alembic/operations/toimpl.py", line 161, in execute_sql
    execution_options=operation.execution_options
  File "/www/lemur-dev/lib/python3.5/site-packages/alembic/ddl/impl.py", line 121, in execute
    self._exec(sql, execution_options)
  File "/www/lemur-dev/lib/python3.5/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/www/lemur-dev/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) enum label "create_cert" already exists
 [SQL: "ALTER TYPE log_type ADD VALUE 'create_cert'"]

```

**Comment by kevgliss** [comment]
Unfortunately adding values to ENUMs in postgres is painful in alembic. Internally when I hit the above error I just re-ran the migration with the following to force it through:

1ae8e3104db8_.py
```
def upgrade():
    connection = None

#    if not op.get_context().as_sql:
#        connection = op.get_bind()
#        connection.execution_options(isolation_level='AUTOCOMMIT')

#     op.execute("ALTER TYPE log_type ADD VALUE 'create_cert'")
#     op.execute("ALTER TYPE log_type ADD VALUE 'update_cert'")

#     if connection is not None:
#         connection.execution_options(isolation_level='READ_COMMITTED')
```

I haven't found a better method as of yet. Hoping someone better with alembic that I might be able to get our ENUMs upgraded more smoothly.

**Comment by kevgliss** [comment]
The idea is that it's complaining the new enum already exists so we shouldn't need to do anything else except upgrade the alembic version.

**Comment by axm862** [comment]
You mention running 1ae8e3104db8_.py, but I cannot locate this file within the lemur files. How exactly do I go about upgrading the alembic version as you said?

**Comment by RickB17** [comment]
Commenting out the lines in 1ae8e3104db8_.py allowed us to get past the ``` lemur -c CONFIGFILE db upgrade ``` issues
