### ISSUE TITLE
KeyError: 'linux-destination' 

### ISSUE THREAD

**Issue by axm862** [Netflix/lemur#867]
After updating Lemur to the newest commit, and running @kevgliss suggestion on resolving the "enum label "create_cert" already exists" by re-running the migration on 1ae8e3104db8_.py after commenting out part of the upgrade() function, I get the following error regarding the Linux-destination plug-in. Any suggestions on how to fix these KeyErrors and TypeErrors? 

```
Exception on /api/1/certificates [GET]
Traceback (most recent call last):
  File "/www/lemur-dev/lib/python3.5/site-packages/marshmallow/utils.py", line 330, in _get_value_for_key
    return obj[key]
TypeError: 'Destination' object is not subscriptable
```

As well as the following: 

```
  File "/www/lemur-dev/lib/python3.5/site-packages/marshmallow/marshalling.py", line 68, in call_and_store
    value = getter_func(data)
  File "/www/lemur-dev/lib/python3.5/site-packages/marshmallow/marshalling.py", line 141, in <lambda>
    getter = lambda d: field_obj.serialize(attr_name, d, accessor=accessor)
  File "/www/lemur-dev/lib/python3.5/site-packages/marshmallow/fields.py", line 243, in serialize
    value = self.get_value(attr, obj, accessor=accessor)
  File "/www/lemur-dev/lib/python3.5/site-packages/marshmallow/fields.py", line 186, in get_value
    return accessor_func(check_key, obj, default)
  File "/www/lemur-dev/lib/python3.5/site-packages/marshmallow/schema.py", line 404, in get_attribute
    return utils.get_value(attr, obj, default)
  File "/www/lemur-dev/lib/python3.5/site-packages/marshmallow/utils.py", line 317, in get_value
    return _get_value_for_keys(key.split('.'), obj, default)
  File "/www/lemur-dev/lib/python3.5/site-packages/marshmallow/utils.py", line 322, in _get_value_for_keys
    return _get_value_for_key(keys[0], obj, default)
  File "/www/lemur-dev/lib/python3.5/site-packages/marshmallow/utils.py", line 333, in _get_value_for_key
    attr = getattr(obj, key)
  File "/www/lemur-dev/lemur/destinations/models.py", line 26, in plugin
    return plugins.get(self.plugin_name)
  File "/www/lemur-dev/lemur/plugins/base/manager.py", line 37, in get
    raise KeyError(slug)
KeyError: 'linux-destination'
```

**Comment by kevgliss** [comment]
@axm862 I believe @RickB17 was facing the same issue, make sure you run `make release` after adding the plugin to setup.py

**Comment by axm862** [comment]
Yup was able to resolve this issue after running make release, thanks!
