### ISSUE TITLE
Release 0.5.0 Module Dependency Issue

### ISSUE THREAD

**Issue by chadhendrie** [Netflix/lemur#873]
We are currently pulling the Lemur code for our deployments from the release 0.5.0 tag. Recently, on startup, Lemur started throwing the following error snippet (full error message is at the end of the post):

```
pkg_resources.ContextualVersionConflict: (cryptography 1.7 (/usr/local/lib64/python3.5/site-packages), Requirement.parse('cryptography>=1.9'), {'PyOpenSSL'})
```

The issue is the latest version of the PyOpenSSL module (17.2.0) has a dependency on the cryptography module with a version of >= 1.9. The 0.5.0 release of setup.py defines the cryptography module version as 1.7 (and does not define an explicit version of PyOpenSSL).

A possible fix for the issue would be to define an explicit version of PyOpenSSL in setup.py. The last release of PyOpenSSL that required cryptography 1.7 is 17.0.0.

```
'pyOpenSSL==17.0.0'
```

Let me know if you'd like me to create a pull request for the fix.

Thanks

Full error message:

```
[ec2-user@ip-10-114-45-39 lemur]$ /usr/local/bin/lemur -c=/etc/lemur/lemur.conf.py start
Traceback (most recent call last):
  File "/usr/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 614, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 920, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 812, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 1.7 (/usr/local/lib64/python3.5/site-packages), Requirement.parse('cryptography>=1.9'), {'PyOpenSSL'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/lemur", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 616, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 629, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 812, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (cryptography 1.7 (/usr/local/lib64/python3.5/site-packages), Requirement.parse('cryptography>=1.9'), {'PyOpenSSL'})

```

**Comment by kevgliss** [comment]
That fix looks like the right one to me. A PR would be great. It might take a little git foo to have this ported to release but we should be able to do something like:
```
$ git checkout -b 0.5_fixes 0.5    # create a bugfix branch
# ... do some work ...
# ... make commits ...
$ git tag 0.5.1
$ git checkout master
$ git merge 0.5_fixes     # merge back, solve merge conflicts if any
$ git branch -d 0.5_fixes # delete the branch, it's not needed anymore
```
Let me know if you run into any issues.

**Comment by kevgliss** [comment]
This has been pushed via: https://github.com/Netflix/lemur/releases/tag/0.5.1

**Comment by chadhendrie** [comment]
Thanks!
