### ISSUE TITLE
make release fails while installing

### ISSUE THREAD

**Issue by r2c2** [Netflix/lemur#884]
Hi, 

I've been trying to install and use lemur several times using the [documentation](http://lemur.readthedocs.io/en/latest/quickstart/index.html).

But I'm always getting the following error when I run the make release step:

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN prefer global marked@0.3.6 should be installed with -g

> gifsicle@3.0.4 postinstall /www/lemur/node_modules/gifsicle
> node lib/install.js

Makefile:24: recipe for target 'release' failed
make: *** [release] Error 1

I'm using ubuntu 16.04 with node version v6.11.2

Thanks in advance.

**Comment by kevgliss** [comment]
Are you using master or some other release tag?

**Comment by r2c2** [comment]
Hi, I'm using master.

**Comment by kevgliss** [comment]
Do you have any other errors? The warnings you mentioned shouldn't cause the command to fail.

**Comment by r2c2** [comment]
No, That's all the output i get.

Should I run the steps manually from the makefile for the release tag?

**Comment by kevgliss** [comment]
Anything you get do to get some more output would be helpful.

**Comment by r2c2** [comment]
When I ran the release steps i found an error in 

```
node_modules/.bin/gulp build
[22:44:51] Using gulpfile /www/lemur/gulpfile.js
[22:44:51] Starting 'build:ngviews'...
[22:44:51] Starting 'dev:styles'...
[22:44:51] Starting 'dev:scripts'...
[22:44:51] Starting 'build:images'...
[22:44:51] Starting 'dev:fonts'...
[22:44:51] Starting 'build:extras'...
[22:44:51] Finished 'build:images' after 21 ms
[22:44:51] Finished 'dev:fonts' after 20 ms
[22:44:51] Starting 'build:fonts'...
[22:44:51] Finished 'build:fonts' after 7.4 ms
[22:44:51] all files 2.02 kB
[22:44:51] Finished 'dev:styles' after 391 ms
[22:44:51] Finished 'build:extras' after 405 ms
[22:44:52] all files 95.99 kB
[22:44:52] Finished 'dev:scripts' after 1.03 s
[22:44:52] all files 102.16 kB
[22:44:52] Finished 'build:ngviews' after 1.13 s
[22:44:52] Starting 'build:inject'...
[22:44:52] 'build:inject' errored after 2.33 ms
[22:44:52] Error: Bower components directory does not exist at /www/lemur/bower_components
    at Error (native)
    at module.exports (/www/lemur/node_modules/main-bower-files/lib/index.js:76:17)
    at injectHtml (/www/lemur/gulp/build.js:147:21)
    at Gulp.<anonymous> (/www/lemur/gulp/build.js:178:10)
    at module.exports (/www/lemur/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/www/lemur/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/www/lemur/node_modules/orchestrator/index.js:214:10)
    at /www/lemur/node_modules/orchestrator/index.js:279:18
    at finish (/www/lemur/node_modules/orchestrator/lib/runTask.js:21:8)
    at /www/lemur/node_modules/orchestrator/lib/runTask.js:52:4
    at f (/www/lemur/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at DestroyableTransform.onend (/www/lemur/node_modules/end-of-stream/index.js:31:18)
    at emitNone (events.js:91:20)
    at DestroyableTransform.emit (events.js:185:7)
    at endReadableNT (/www/lemur/node_modules/readable-stream/lib/_stream_readable.js:992:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```
 
I created the directory `/www/lemur/bower_components` . After this the command ran successfully, however when I start lemur with :
` lemur start -b my-ip-address:8000 `
I get the error in the browser "The requested URL was not found on the server".

**Comment by kevgliss** [comment]
Which url are you attempting to hit? By default the api server has nothing attached to the root. Something like /api/1/healthcheck should work though.

**Comment by Mopkillaaa** [comment]
Hi, 
like r2c2 i tried to install Lemur on Ubuntu 14.04 serveral times following your documentation.
On the `make release` step i always get the following errors:

> npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /www/lemur/npm-debug.log
npm ERR! not ok code 0
make: *** [release] Error 1

the npm-debug.log shows the following errors:

> 260730 error TypeError: Cannot read property 'latest' of undefined
260730 error     at next (/usr/share/npm/lib/cache.js:687:35)
260730 error     at /usr/share/npm/lib/cache.js:675:5
260730 error     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
260730 error     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
260730 error     at Object.oncomplete (fs.js:107:15)
260731 error If you need help, you may report this log at:
260731 error     <http://github.com/isaacs/npm/issues>
260731 error or email it to:
260731 error     <npm-@googlegroups.com>
260732 error System Linux 3.16.0-30-generic
260733 error command "/usr/bin/nodejs" "/usr/bin/npm" "install"
260734 error cwd /www/lemur
260735 error node -v v0.10.25
260736 error npm -v 1.3.10
260737 error type non_object_property_load
260738 verbose exit [ 1, true ]
cat: l: No such file or directory

Thanks in advance.

**Comment by kevgliss** [comment]
Please use a newer version of node. See #886.

**Comment by r2c2** [comment]
Hi @kevgliss 

Thanks for your help!

After testing the URL that you provided it works ok, but when i'm trying to login to  `http://ip-address/#/login` the page shows without style and the browser console shows:

`ReferenceError: angular is not defined`

Thanks in advance

**Comment by kevgliss** [comment]
What version of node are you running? Have you run make release?

**Comment by r2c2** [comment]
Hi, It seems that after running `make release` again after creating the folder `/www/lemur/bower_components `
it's working now, thanks a lot for your help.
