### ISSUE TITLE
db missing column error when updating to latest on master

### ISSUE THREAD

**Issue by pr8kerl** [Netflix/lemur#897]
I've been running an internal server directly from master for a bit. I was at commit 7507f6be501a23adef23f2ae21a4b76abcad47aa.
Now when I go to update my install to the latest. I am getting DB issues around column rotation policy missing.

I believe any DB migrations occur automatically at startup. I'm not too familiar with how they work.

Here are the steps to reproduce on a clean install.

* git checkout 7507f6be501a23adef23f2ae21a4b76abcad47aa
  Checkout from master from around start of July.
  Startup postgres/lemur. 

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> 8ae67285ff14
```

* All good. Create a CA and a certificate without issue.
* shutdown lemur/postgres.
* git checkout master

HEAD is now c0784b40e033ab8cbb146226dece70dfb2591ca4

* start postgres/lemur

```
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision 8ae67285ff14 -> 1ae8e3104db8
```

* access the index web page and get the following errors.

```
postgres_1  | ERROR:  column certificates.rotation_policy_id does not exist at character 1126
postgres_1  | STATEMENT:  SELECT count(*) AS count_1 
postgres_1  | 	FROM (SELECT certificates.id AS certificates_id, certificates.owner AS certificates_owner, certificates.name AS certificates_name, certificates.description AS certificates_description, certificates.notify AS certificates_notify, certificates.body AS certificates_body, certificates.chain AS certificates_chain, certificates.private_key AS certificates_private_key, certificates.issuer AS certificates_issuer, certificates.serial AS certificates_serial, certificates.cn AS certificates_cn, certificates.deleted AS certificates_deleted, certificates.not_before AS certificates_not_before, certificates.not_after AS certificates_not_after, certificates.date_created AS certificates_date_created, certificates.signing_algorithm AS certificates_signing_algorithm, certificates.status AS certificates_status, certificates.bits AS certificates_bits, certificates.san AS certificates_san, certificates.rotation AS certificates_rotation, certificates.user_id AS certificates_user_id, certificates.authority_id AS certificates_authority_id, certificates.root_authority_id AS certificates_root_authority_id, certificates.rotation_policy_id AS certificates_rotation_policy_id 
postgres_1  | 	FROM certificates ORDER BY certificates.id DESC) AS anon_1
lemur_1     | --------------------------------------------------------------------------------
lemur_1     | ERROR in schema [/opt/app/lemur/lemur/common/schema.py:163]:
lemur_1     | (psycopg2.ProgrammingError) column certificates.rotation_policy_id does not exist
lemur_1     | LINE 2: ...t_authority_id AS certificates_root_authority_id, certificat...
lemur_1     |                                                              ^
lemur_1     |  [SQL: 'SELECT count(*) AS count_1 \nFROM (SELECT certificates.id AS certificates_id, certificates.owner AS certificates_owner, certificates.name AS certificates_name, certificates.description AS certificates_description, certificates.notify AS certificates_notify, certificates.body AS certificates_body, certificates.chain AS certificates_chain, certificates.private_key AS certificates_private_key, certificates.issuer AS certificates_issuer, certificates.serial AS certificates_serial, certificates.cn AS certificates_cn, certificates.deleted AS certificates_deleted, certificates.not_before AS certificates_not_before, certificates.not_after AS certificates_not_after, certificates.date_created AS certificates_date_created, certificates.signing_algorithm AS certificates_signing_algorithm, certificates.status AS certificates_status, certificates.bits AS certificates_bits, certificates.san AS certificates_san, certificates.rotation AS certificates_rotation, certificates.user_id AS certificates_user_id, certificates.authority_id AS certificates_authority_id, certificates.root_authority_id AS certificates_root_authority_id, certificates.rotation_policy_id AS certificates_rotation_policy_id \nFROM certificates ORDER BY certificates.id DESC) AS anon_1']
lemur_1     | 
lemur_1     | 
lemur_1     | 
lemur_1     | The above exception was the direct cause of the following exception:
lemur_1     | 
lemur_1     | Traceback (most recent call last):
lemur_1     |   File "/opt/app/lemur/lemur/common/schema.py", line 160, in decorated_function
lemur_1     |     resp = f(*args, **kwargs)
lemur_1     |   File "/opt/app/lemur/lemur/certificates/views.py", line 135, in get
lemur_1     |     return service.render(args)
lemur_1     |   File "/opt/app/lemur/lemur/certificates/service.py", line 334, in render
lemur_1     |     return database.sort_and_page(query, Certificate, args)
lemur_1     |   File "/opt/app/lemur/lemur/database.py", line 291, in sort_and_page
lemur_1     |     total = query.count()
lemur_1     |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3089, in count
lemur_1     |     return self.from_self(col).scalar()
lemur_1     |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2843, in scalar
lemur_1     |     ret = self.one()
lemur_1     |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2814, in one
lemur_1     |     ret = self.one_or_none()
lemur_1     |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
lemur_1     |     ret = list(self)
lemur_1     |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
lemur_1     |     return self._execute_and_instances(context)
lemur_1     |   File "/usr/local/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
lemur_1     |     result = conn.execute(querycontext.statement, self._params)
```

* the current db revision shows the following

```
root@0b0ed4429c36:/opt/app/lemur/lemur# lemur -c ../lemur.conf.py db show
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'ACMEIssuerPlugin' may not work correctly. Required variable 'ACME_DIRECTORY_URL' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Rev: 1ae8e3104db8 (head)
Parent: a02a678ddc25
Path: /opt/app/lemur/lemur/migrations/versions/1ae8e3104db8_.py

    Adds additional ENUM for creating and updating certificates.
    
    Revision ID: 1ae8e3104db8
    Revises: a02a678ddc25
    Create Date: 2017-07-13 12:32:09.162800

root@0b0ed4429c36:/opt/app/lemur/lemur#
```

Got any tips on how to resolve this??
Let me know if you need any more info.

Thanks.

**Comment by kevgliss** [comment]
Lemur doesn't run any migrations on startup... how are you starting the app? Via `lemur start` or some other method?

Are you following the docs via located here: 

http://lemur.readthedocs.io/en/latest/administration.html?highlight=upgrading#upgrading-lemur 

and running `lemur db upgrade`?

I try to make a note in each release if this is necessary, but if you're pulling from master it's good practice to run this command every time you pull. If your database is already up-to-date it should have no effect on the database itself. 

Once you run that command you will also probably encounter #859. I have yet to figure out a good solution for that migration. 

I'd also be interested to see the output of `lemur db current` in order to determine which version of that database you're currently running.

**Comment by pr8kerl** [comment]
Thanks for the pointers. I hope this isn't down to me.

During my troubleshooting I did run an upgrade. But just judging by the alembic messages on startup, I kinda assumed that there must be a migration happening - especially those stamp revision messages look like it.

But in my steps to update to latest master, I still have the same error after explicitly running the db upgrade step.

Am running off latest master.
Current db version
```
root@0b0ed4429c36:/opt/app/lemur/lemur# lemur -c ../lemur.conf.py db current
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'ACMEIssuerPlugin' may not work correctly. Required variable 'ACME_DIRECTORY_URL' is not set in Lemur's conf.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
1ae8e3104db8 (head)
```

Do an upgrade
```
root@0b0ed4429c36:/opt/app/lemur/lemur# lemur -c ../lemur.conf.py db upgrade
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'ACMEIssuerPlugin' may not work correctly. Required variable 'ACME_DIRECTORY_URL' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
```

No obvious change
```
root@0b0ed4429c36:/opt/app/lemur/lemur# lemur -c ../lemur.conf.py db current
Plugin 'ACMEIssuerPlugin' may not work correctly. Required variable 'ACME_DIRECTORY_URL' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
1ae8e3104db8 (head)
```


I then try again hitting web page and same error about rotation policy.
```
postgres_1  | ERROR:  column certificates.rotation_policy_id does not exist at character 1126
postgres_1  | STATEMENT:  SELECT count(*) AS count_1 
postgres_1  | 	FROM (SELECT certificates.id AS certificates_id, certificates.owner AS certificates_owner, certificates.name AS certificates_name, certificates.description AS certificates_description, certificates.notify AS certificates_notify, certificates.body AS certificates_body, certificates.chain AS certificates_chain, certificates.private_key AS certificates_private_key, certificates.issuer AS certificates_issuer, certificates.serial AS certificates_serial, certificates.cn AS certificates_cn, certificates.deleted AS certificates_deleted, certificates.not_before AS certificates_not_before, certificates.not_after AS certificates_not_after, certificates.date_created AS certificates_date_created, certificates.signing_algorithm AS certificates_signing_algorithm, certificates.status AS certificates_status, certificates.bits AS certificates_bits, certificates.san AS certificates_san, certificates.rotation AS certificates_rotation, certificates.user_id AS certificates_user_id, certificates.authority_id AS certificates_authority_id, certificates.root_authority_id AS certificates_root_authority_id, certificates.rotation_policy_id AS certificates_rotation_policy_id 
postgres_1  | 	FROM certificates ORDER BY certificates.id DESC) AS anon_1
lemur_1     | --------------------------------------------------------------------------------
lemur_1     | ERROR in schema [/opt/app/lemur/lemur/common/schema.py:163]:
lemur_1     | (psycopg2.ProgrammingError) column certificates.rotation_policy_id does not exist
lemur_1     | LINE 2: ...t_authority_id AS certificates_root_authority_id, certificat...
lemur_1     |                                                              ^
```

And on our local dev environment we start lemur with the following.
We run the init every time - hope that's ok. I think it will only create stuff if it is missing for an empty db scenario.
```
lemur init -p ${INIT_PASSWORD} 
lemur runserver -h 0.0.0.0 -p ${LEMUR_PORT} -d -r

**Comment by kevgliss** [comment]
You should not run the `init` every time, that should only be run when Lemur is first being setup. 

This is what I believe is happening:

`lemur init` does quite a few things, but the most important one to this issue being that it `stamps` the database as current (http://alembic.zzzcomputing.com/en/latest/api/commands.html#alembic.command.stamp). This was to save new users from running migrations needlessly (if the database has just been created there is nothing to migrate). 

As you are running this every time you have `stamped` yourself to the newest revision `1ae8e3104db8`, however that's not really the case as you've never run any of the migrations required to get to `1ae8e3104db8`. 

Do you happen to remember which version you were on previously? I would recommend you manually edit the `alembic_version` table, setting `version_num` to your last known configuration (most likely `8ae67285ff14`) and then upgrade the db by running `lemur db upgrade`.  

Again, you will run into #859. Where you will need to run the migration and then run it again with some of the migration commented out.

**Comment by pr8kerl** [comment]
@kevgliss thank you! It was just as you said.
I set the alembic_version back to `8ae67285ff14` and ran the upgrade. And had to comment out the bit as described in #859. And now I am at `1ae8e3104db8`. :+1: 
I've removed the init step from our startup now so I won't run into this again. I am learning.
Thanks a lot for your help.
