### ISSUE TITLE
db upgrade results in type "log_type" does not exist

### ISSUE THREAD

**Issue by RickB17** [Netflix/lemur#925]
Previously when this line was referenced we commented it out. I believe that was because it stated the operation was already complete, this error is stating that it doesn't exist. I'm assuming it's not so safe to simply comment it out. @kevgliss  could you confirm?

https://github.com/Netflix/lemur/blob/61c493fc9196a61bb48b07ceb719d6bc36f12ee9/lemur/migrations/versions/1ae8e3104db8_.py#L23

```` (lemur) lemur@SERVERNAME:/www/lemur/lemur$ lemur -c /home/lemur/.lemur/lemur.conf.py db upgrade
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'ACMEIssuerPlugin' may not work correctly. Required variable 'ACME_DIRECTORY_URL' is not set in Lemur's conf.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 7f71c0cea31a -> 932525b82f1a, Changing the column name to the more accurately named 'notify'.
INFO  [alembic.runtime.migration] Running upgrade 932525b82f1a -> e3691fc396e9, Adding logging database tables.
INFO  [alembic.runtime.migration] Running upgrade e3691fc396e9 -> 131ec6accff5, Ensuring we have endpoint updated times and certificate rotation availability.
INFO  [alembic.runtime.migration] Running upgrade 131ec6accff5 -> 5e680529b666, Sync up endpoints properties
INFO  [alembic.runtime.migration] Running upgrade 5e680529b666 -> 8ae67285ff14, Modifies the unique index for the certificate replacements
INFO  [alembic.runtime.migration] Running upgrade 8ae67285ff14 -> a02a678ddc25, Adds support for rotation policies.
INFO  [alembic.runtime.migration] Running upgrade a02a678ddc25 -> 1ae8e3104db8, Adds additional ENUM for creating and updating certificates.
/www/lemur/lib/python3.5/site-packages/sqlalchemy/engine/default.py:428: SAWarning: Connection is already established with a Transaction; setting isolation_level may implicitly rollback or commit the existing transaction, or have no effect until next transaction
  "Connection is already established with a Transaction; "
Traceback (most recent call last):
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: type "log_type" does not exist


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/www/lemur/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/www/lemur/lemur/manage.py", line 545, in main
    manager.run()
  File "/www/lemur/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/www/lemur/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/www/lemur/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/www/lemur/lib/python3.5/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/www/lemur/lib/python3.5/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/www/lemur/lib/python3.5/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/www/lemur/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/www/lemur/lib/python3.5/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 72, in <module>
    run_migrations_online()
  File "migrations/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/www/lemur/lib/python3.5/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/www/lemur/lib/python3.5/site-packages/alembic/runtime/migration.py", line 330, in run_migrations
    step.migration_fn(**kw)
  File "/www/lemur/lemur/migrations/versions/1ae8e3104db8_.py", line 23, in upgrade
    op.execute("ALTER TYPE log_type ADD VALUE 'create_cert'")
  File "<string>", line 8, in execute
  File "<string>", line 3, in execute
  File "/www/lemur/lib/python3.5/site-packages/alembic/operations/ops.py", line 1856, in execute
    return operations.invoke(op)
  File "/www/lemur/lib/python3.5/site-packages/alembic/operations/base.py", line 318, in invoke
    return fn(self, operation)
  File "/www/lemur/lib/python3.5/site-packages/alembic/operations/toimpl.py", line 161, in execute_sql
    execution_options=operation.execution_options
  File "/www/lemur/lib/python3.5/site-packages/alembic/ddl/impl.py", line 121, in execute
    self._exec(sql, execution_options)
  File "/www/lemur/lib/python3.5/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) type "log_type" does not exist
 [SQL: "ALTER TYPE log_type ADD VALUE 'create_cert'"]
```

**Comment by RickB17** [comment]
I attempted to manual create the type in the postgres database:
``` CREATE TYPE log_type AS ENUM ('key_view', 'create_cert', 'update_cert'); ```
this got passed the error of the type not existing, then we commented out lines during the upgrade that reference items that "already exist" and landed on this:

```
(lemur) lemur@SERVERNAME:/www/lemur/lemur$ lemur -c /home/lemur/.lemur/lemur.conf.py db upgrade
Plugin 'ACMEIssuerPlugin' may not work correctly. Required variable 'ACME_DIRECTORY_URL' is not set in Lemur's conf.
Plugin 'DigiCertIssuerPlugin' may not work correctly. Required variable 'DIGICERT_API_KEY' is not set in Lemur's conf.
Plugin 'DigiCertCISIssuerPlugin' may not work correctly. Required variable 'DIGICERT_CIS_API_KEY' is not set in Lemur's conf.
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade 7f71c0cea31a -> 932525b82f1a, Changing the column name to the more accurately named 'notify'.
INFO  [alembic.runtime.migration] Running upgrade 932525b82f1a -> e3691fc396e9, Adding logging database tables.
INFO  [alembic.runtime.migration] Running upgrade e3691fc396e9 -> 131ec6accff5, Ensuring we have endpoint updated times and certificate rotation availability.
INFO  [alembic.runtime.migration] Running upgrade 131ec6accff5 -> 5e680529b666, Sync up endpoints properties
INFO  [alembic.runtime.migration] Running upgrade 5e680529b666 -> 8ae67285ff14, Modifies the unique index for the certificate replacements
INFO  [alembic.runtime.migration] Running upgrade 8ae67285ff14 -> a02a678ddc25, Adds support for rotation policies.
INFO  [alembic.runtime.migration] Running upgrade a02a678ddc25 -> 1ae8e3104db8, Adds additional ENUM for creating and updating certificates.
/www/lemur/lib/python3.5/site-packages/sqlalchemy/engine/default.py:428: SAWarning: Connection is already established with a Transaction; setting isolation_level may implicitly rollback or commit the existing transaction, or have no effect until next transaction
  "Connection is already established with a Transaction; "
Traceback (most recent call last):
  File "/www/lemur/bin/lemur", line 11, in <module>
    load_entry_point('lemur', 'console_scripts', 'lemur')()
  File "/www/lemur/lemur/manage.py", line 545, in main
    manager.run()
  File "/www/lemur/lib/python3.5/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/www/lemur/lib/python3.5/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/www/lemur/lib/python3.5/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/www/lemur/lib/python3.5/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/www/lemur/lib/python3.5/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/www/lemur/lib/python3.5/site-packages/alembic/script/base.py", line 425, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/www/lemur/lib/python3.5/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/www/lemur/lib/python3.5/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "migrations/env.py", line 72, in <module>
    run_migrations_online()
  File "migrations/env.py", line 65, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/www/lemur/lib/python3.5/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/www/lemur/lib/python3.5/site-packages/alembic/runtime/migration.py", line 337, in run_migrations
    head_maintainer.update_to_step(step)
  File "/www/lemur/lib/python3.5/site-packages/alembic/runtime/migration.py", line 540, in update_to_step
    self._update_version(from_, to_)
  File "/www/lemur/lib/python3.5/site-packages/alembic/runtime/migration.py", line 507, in _update_version
    % (from_, to_, self.context.version_table, ret.rowcount))
alembic.util.exc.CommandError: Online migration expected to match one row when updating 'a02a678ddc25' to '1ae8e3104db8' in 'alembic_version'; 0 found
```

**Comment by kevgliss** [comment]
Hmm, I'm not sure I've ever see that error before. What are your starting and ending database versions? Are you simply trying to get to latest? 

I'd be hesitant about simply commenting out this first line you mentioned because `psycopg2.ProgrammingError: type "log_type" does not exist` should exist. 

Per: https://github.com/Netflix/lemur/blob/727bc87ede78eab1abf00155958d71564a8ed40e/lemur/migrations/versions/e3691fc396e9_.py#L22

I would double check your tables, specifically the `alembic_version` table, it's expecting `a02a678ddc25` such that it can upgrade to `1ae8e3104db8` but the error would make it seem as though `a02a678ddc25` isn't the current version of your database.

If you *know* what the last competed version is you can manually replace the version. If not it might take a little more digging to try to figure out.

**Comment by RickB17** [comment]
Below is the output from ``` select * from alembic_version ```. I'm going to make a clone of my instance and run through the process one again. 

Based on the output ```INFO  [alembic.runtime.migration] Running upgrade 932525b82f1a -> e3691fc396e9, Adding logging database tables. ```  , is it a good assumption to say that the https://github.com/Netflix/lemur/blob/727bc87ede78eab1abf00155958d71564a8ed40e/lemur/migrations/versions/e3691fc396e9_.py#L22 is not executing properly for some reason?

``` lemur=> select * from alembic_version;
 version_num
--------------
 7f71c0cea31a
(1 row)

```

**Comment by RickB17** [comment]
When I display the tables in the lemur database there is no log table. Should this table be created with one of the alembic migration scripts:

https://github.com/Netflix/lemur/blob/f7668718241c5a937d8736e00a6bbbdc7b8a5e95/lemur/migrations/versions/e3691fc396e9_.py#L17-L29

```
                       List of relations
 Schema |                 Name                  | Type  | Owner
--------+---------------------------------------+-------+-------
 public | alembic_version                       | table | lemur
 public | authorities                           | table | lemur
 public | certificate_associations              | table | lemur
 public | certificate_destination_associations  | table | lemur
 public | certificate_notification_associations | table | lemur
 public | certificate_replacement_associations  | table | lemur
 public | certificate_source_associations       | table | lemur
 public | certificates                          | table | lemur
 public | ciphers                               | table | lemur
 public | destinations                          | table | lemur
 public | domains                               | table | lemur
 public | endpoints                             | table | lemur
 public | notifications                         | table | lemur
 public | policies_ciphers                      | table | lemur
 public | policy                                | table | lemur
 public | roles                                 | table | lemur
 public | roles_authorities                     | table | lemur
 public | roles_certificates                    | table | lemur
 public | roles_users                           | table | lemur
 public | sources                               | table | lemur
 public | users                                 | table | lemur

```

**Comment by kevgliss** [comment]
Yes, it should be created. 

Can you run `alembic upgrade --sql > migration.sql`? I'd be interested to see what SQL alembic is generating here.

**Comment by RickB17** [comment]
```
BEGIN;

CREATE TABLE alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

-- Running upgrade  -> 33de094da890

CREATE TABLE certificate_replacement_associations (
    replaced_certificate_id INTEGER,
    certificate_id INTEGER,
    FOREIGN KEY(certificate_id) REFERENCES certificates (id) ON DELETE cascade,
    FOREIGN KEY(replaced_certificate_id) REFERENCES certificates (id) ON DELETE cascade
);

INSERT INTO alembic_version (version_num) VALUES ('33de094da890');

-- Running upgrade 33de094da890 -> 4c50b903d1ae

ALTER TABLE domains ADD COLUMN sensitive BOOLEAN;

UPDATE alembic_version SET version_num='4c50b903d1ae' WHERE alembic_version.version_num = '33de094da890';

-- Running upgrade 4c50b903d1ae -> 412b22cb656a

CREATE TABLE roles_authorities (
    authority_id INTEGER,
    role_id INTEGER,
    FOREIGN KEY(authority_id) REFERENCES authorities (id),
    FOREIGN KEY(role_id) REFERENCES roles (id)
);

CREATE UNIQUE INDEX roles_authorities_ix ON roles_authorities (authority_id, role_id);

CREATE TABLE roles_certificates (
    certificate_id INTEGER,
    role_id INTEGER,
    FOREIGN KEY(certificate_id) REFERENCES certificates (id),
    FOREIGN KEY(role_id) REFERENCES roles (id)
);

CREATE UNIQUE INDEX roles_certificates_ix ON roles_certificates (certificate_id, role_id);

CREATE UNIQUE INDEX certificate_associations_ix ON certificate_associations (domain_id, certificate_id);

CREATE UNIQUE INDEX certificate_destination_associations_ix ON certificate_destination_associations (destination_id, certificate_id);

CREATE UNIQUE INDEX certificate_notification_associations_ix ON certificate_notification_associations (notification_id, certificate_id);

CREATE UNIQUE INDEX certificate_replacement_associations_ix ON certificate_replacement_associations (certificate_id, certificate_id);

CREATE UNIQUE INDEX certificate_source_associations_ix ON certificate_source_associations (source_id, certificate_id);

CREATE UNIQUE INDEX roles_users_ix ON roles_users (user_id, role_id);

select id, authority_id from roles where authority_id is not null;

```

**Comment by RickB17** [comment]
Is there a quick way to verify the database connectivity from within ``` lemur shell ``` ?

I believe the last errors may be related to a database connection issue. I know the postgres database is online because I can execute queries against it from psql.

**Comment by RickB17** [comment]
I believe I verified the database connection via the following and results were prints
```
import lemur
db = lemur.database.db
certs = db.engine.execute("SELECT * FROM certificates")
for cert in certs:
    print(cert)


```

**Comment by kevgliss** [comment]
This is how we do it for the health check:
```
    with db.engine.connect() as connection:
        connection.execute('SELECT 1;')
```

**Comment by RickB17** [comment]
I think I just learned something important about the --sql flag, it runs it in offline mode. I believe that is why it was returning the ``` TypeError: <flask_script.commands.Command object at 0x7fead4fab630>: 'NoneType' object is not iterable ```

**Comment by kevgliss** [comment]
The work arounds look Okay by me and shouldn't impact anything going forward. Hopefully your database is in a better place. 

I'm not quite sure why 1 by 1 migration would work and full migration wouldn't. I haven't seen that, although we typically upgrade the database frequently.

**Comment by kevgliss** [comment]
I've since found the excellent https://github.com/dw/alembic-autogenerate-enums which should help address the ENUM issue at least. I've backported the migrations to use this package. 

Closing this for now as I believe you are in a decent state.
