### ISSUE TITLE
verisign plugin use with lemur

### ISSUE THREAD

**Issue by develtech1** [Netflix/lemur#956]
Hi, 
I am getting following issue while using  verisign plugin. 

```
[2017-10-03 19:21:40,027] ERROR in schema: 'NoneType' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 160, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/authorities/views.py", line 223, in post
    return service.create(**data)
  File "/www/lemur/lemur/authorities/service.py", line 107, in create
    cert = upload(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 222, in upload
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/www/lemur/lemur/certificates/models.py", line 130, in __init__
    cert = lemur.common.utils.parse_certificate(kwargs['body'])
  File "/www/lemur/lemur/common/utils.py", line 53, in parse_certificate
    return x509.load_pem_x509_certificate(body, default_backend())
  File "/www/lemur/lib/python3.5/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1063, in load_pem_x509_certificate
    mem_bio = self._bytes_to_bio(data)
  File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 432, in _bytes_to_bio
    data_char_p = self._ffi.new("char[]", data)
TypeError: 'NoneType' object cannot be interpreted as an integer
2017-10-03 19:21:40,027 ERROR: 'NoneType' object cannot be interpreted as an integer [in /www/lemur/lemur/common/schema.py:163]
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 160, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/authorities/views.py", line 223, in post
    return service.create(**data)
  File "/www/lemur/lemur/authorities/service.py", line 107, in create
    cert = upload(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 222, in upload
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/www/lemur/lemur/certificates/models.py", line 130, in __init__
    cert = lemur.common.utils.parse_certificate(kwargs['body'])
  File "/www/lemur/lemur/common/utils.py", line 53, in parse_certificate
    return x509.load_pem_x509_certificate(body, default_backend())
  File "/www/lemur/lib/python3.5/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1063, in load_pem_x509_certificate
    mem_bio = self._bytes_to_bio(data)
  File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 432, in _bytes_to_bio
    data_char_p = self._ffi.new("char[]", data)
TypeError: 'NoneType' object cannot be interpreted as an integer
'NoneType' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/www/lemur/lemur/common/schema.py", line 160, in decorated_function
    resp = f(*args, **kwargs)
  File "/www/lemur/lemur/authorities/views.py", line 223, in post
    return service.create(**data)
  File "/www/lemur/lemur/authorities/service.py", line 107, in create
    cert = upload(**kwargs)
  File "/www/lemur/lemur/certificates/service.py", line 222, in upload
    cert = Certificate(**kwargs)
  File "<string>", line 4, in __init__
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 414, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/www/lemur/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 411, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/www/lemur/lemur/certificates/models.py", line 130, in __init__
    cert = lemur.common.utils.parse_certificate(kwargs['body'])
  File "/www/lemur/lemur/common/utils.py", line 53, in parse_certificate
    return x509.load_pem_x509_certificate(body, default_backend())
  File "/www/lemur/lib/python3.5/site-packages/cryptography/x509/base.py", line 43, in load_pem_x509_certificate
    return backend.load_pem_x509_certificate(data)
  File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1063, in load_pem_x509_certificate
    mem_bio = self._bytes_to_bio(data)
  File "/www/lemur/lib/python3.5/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 432, in _bytes_to_bio
    data_char_p = self._ffi.new("char[]", data)
**TypeError: 'NoneType' object cannot be interpreted as an integer**
```

Following are my configuration.   should i sign up for versign configuration parameters. 
Please guide. 
```

# This is just Python which means you can inherit and tweak settings

import os
_basedir = os.path.abspath(os.path.dirname(__file__))

THREADS_PER_PAGE = 8

# General

# These will need to be set to `True` if you are developing locally
CORS = False
debug = False

# this is the secret key used by flask session management
SECRET_KEY = 'xxx'  

# You should consider storing these separately from your config
LEMUR_TOKEN_SECRET = 'xxxx'
LEMUR_ENCRYPTION_KEYS = 'xxxxxx'

# List of domain regular expressions that non-admin users can issue
LEMUR_WHITELISTED_DOMAINS = []

# Mail Server

LEMUR_EMAIL = 'test@gmail.com'
LEMUR_SECURITY_TEAM_EMAIL = ['test@gmail.com']
#LEMUR_EMAIL = ''
#LEMUR_SECURITY_TEAM_EMAIL = []

# Certificate Defaults

LEMUR_DEFAULT_COUNTRY = 'US'
LEMUR_DEFAULT_STATE = 'CAL'
LEMUR_DEFAULT_LOCATION = 'NEWYORK'
LEMUR_DEFAULT_ORGANIZATION = 'ABC'
LEMUR_DEFAULT_ORGANIZATIONAL_UNIT = 'Google'
# Authentication Providers

ACTIVE_PROVIDERS = []

# Logging

LOG_LEVEL = "DEBUG"
LOG_FILE = "lemur.log"


# Database

# modify this if you are not using a local database
SQLALCHEMY_DATABASE_URI = 'postgresql://lemur:lemur@localhost:5432/lemur'

# AWS

LEMUR_INSTANCE_PROFILE = 'Lemur'

# Issuers

# These will be dependent on which 3rd party that Lemur is
# configured to use.

LEMUR_DEFAULT_ISSUER_PLUGIN = "verisign-issuer"
LEMUR_DEFAULT_AUTHORITY = "verisign"
VERISIGN_URL = 'https://verisign.com'
VERISIGN_PEM_PATH = '~/'
VERISIGN_FIRST_NAME = 'jim'
VERISIGN_LAST_NAME = 'bob'
VERSIGN_EMAIL = 'jim@verisign.com'

```
---------------------

**Comment by kevgliss** [comment]
I don't believe this is a valid path`VERISIGN_PEM_PATH = '~/' it should be the full path to your verisign/symantec client certificate.

Additionally `VERISIGN_URL = 'https://verisign.com'` I don't believe this url is correct, for instance our integration points to: `VERISIGN_URL = "https://certmanager-webservices.websecurity.symantec.com/vswebservices"`.

 I'm not sure what kind of account you have with symantec/verisign so your mileage may vary.

A couple other things don't make sense in your config:

```
LEMUR_DEFAULT_COUNTRY = 'US'
LEMUR_DEFAULT_STATE = 'CAL'
LEMUR_DEFAULT_LOCATION = 'NEWYORK'
LEMUR_DEFAULT_ORGANIZATION = 'ABC'
LEMUR_DEFAULT_ORGANIZATIONAL_UNIT = 'Google'
```
Now hopefully these have just been changed for posting but these values will have to be verified with the CA, so obviously the location can't be New York and the State be CAL.

**Comment by develtech1** [comment]
Hi,
Thanks for response and guidance. I was trying to generate certificate using lemur. Can i generates certificates without subscribing verisign or digicert etc ?

**Comment by kevgliss** [comment]
If you use the `cryptography` issuer you don't need digicert or verisign, however these are `self-signed` certificates and will not be publically trusted.

**Comment by develtech1** [comment]
okay Sir. 
Thanks.
